/*
 FileSaver.js
  A saveAs() FileSaver implementation.
  2014-01-24

  By Eli Grey, http://eligrey.com
  License: X11/MIT
    See LICENSE.md
 @source http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js */
 var saveAs=saveAs||"undefined"!==typeof navigator&&navigator.msSaveOrOpenBlob&&navigator.msSaveOrOpenBlob.bind(navigator)||function(b){if("undefined"===typeof navigator||!/MSIE [1-9]\./.test(navigator.userAgent)){var u=b.document,I=b.URL||b.webkitURL||b,p=u.createElementNS("http://www.w3.org/1999/xhtml","a"),J=!b.externalHost&&"download"in p,w=b.webkitRequestFileSystem,A=b.requestFileSystem||w||b.mozRequestFileSystem,K=function(a){(b.setImmediate||b.setTimeout)(function(){throw a;},0)},B=0,q=[],x=
 function(){for(var a=q.length;a--;){var d=q[a];"string"===typeof d?I.revokeObjectURL(d):d.remove()}q.length=0},y=function(a,d,c){d=[].concat(d);for(var f=d.length;f--;){var r=a["on"+d[f]];if("function"===typeof r)try{r.call(a,c||a)}catch(v){K(v)}}},G=function(a,d){var c=this,f=a.type,r=!1,v=function(){var l=(b.URL||b.webkitURL||b).createObjectURL(a);q.push(l);return l},C=function(){y(c,["writestart","progress","write","writeend"])},h=function(){if(r||!t)t=v(a);z?z.location.href=t:window.open(t,"_blank");
 c.readyState=c.DONE;C()},m=function(l){return function(){if(c.readyState!==c.DONE)return l.apply(this,arguments)}},D={create:!0,exclusive:!1};c.readyState=c.INIT;d||(d="download");if(J){var t=v(a);u=b.document;p=u.createElementNS("http://www.w3.org/1999/xhtml","a");p.href=t;p.download=d;f=u.createEvent("MouseEvents");f.initMouseEvent("click",!0,!1,b,0,0,0,0,0,!1,!1,!1,!1,0,null);p.dispatchEvent(f);c.readyState=c.DONE;C()}else{if(b.chrome&&f&&"application/octet-stream"!==f){var L=a.slice||a.webkitSlice;
 a=L.call(a,0,a.size,"application/octet-stream");r=!0}w&&"download"!==d&&(d+=".download");if("application/octet-stream"===f||w)var z=b;A?(B+=a.size,A(b.TEMPORARY,B,m(function(l){l.root.getDirectory("saved",D,m(function(E){var F=function(){E.getFile(d,D,m(function(g){g.createWriter(m(function(n){n.onwriteend=function(k){z.location.href=g.toURL();q.push(g);c.readyState=c.DONE;y(c,"writeend",k)};n.onerror=function(){var k=n.error;k.code!==k.ABORT_ERR&&h()};["writestart","progress","write","abort"].forEach(function(k){n["on"+
 k]=c["on"+k]});n.write(a);c.abort=function(){n.abort();c.readyState=c.DONE};c.readyState=c.WRITING}),h)}),h)};E.getFile(d,{create:!1},m(function(g){g.remove();F()}),m(function(g){g.code===g.NOT_FOUND_ERR?F():h()}))}),h)}),h)):h()}},e=G.prototype,H=function(a,d){return new G(a,d)};e.abort=function(){this.readyState=this.DONE;y(this,"abort")};e.readyState=e.INIT=0;e.WRITING=1;e.DONE=2;e.error=e.onwritestart=e.onprogress=e.onwrite=e.onabort=e.onerror=e.onwriteend=null;b.addEventListener("unload",x,!1);
 H.unload=function(){x();b.removeEventListener("unload",x,!1)};return H}}("undefined"!==typeof self&&self||"undefined"!==typeof window&&window||this.content);"undefined"!==typeof module&&(module.exports=saveAs);