/*
 JSZip v3.5.0 - A JavaScript class for generating and reading zip files
<http://stuartk.com/jszip>

(c) 2009-2016 Stuart Knightley <stuart [at] stuartk.com>
Dual licenced under the MIT license or GPLv3. See https://raw.github.com/Stuk/jszip/master/LICENSE.markdown.

JSZip uses the library pako released under the MIT license :
https://github.com/nodeca/pako/blob/master/LICENSE
*/
(function(aa){"object"===typeof exports&&"undefined"!==typeof module?module.exports=aa():"function"===typeof define&&define.amd?define([],aa):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).JSZip=aa()})(function(){return function m(p,J,B){function w(u,t){if(!J[u]){if(!p[u]){var l="function"==typeof require&&require;if(!t&&l)return l(u,!0);if(e)return e(u,!0);l=Error("Cannot find module '"+u+"'");throw l.code="MODULE_NOT_FOUND",l;}l=J[u]=
{exports:{}};p[u][0].call(l.exports,function(x){var d=p[u][1][x];return w(d?d:x)},l,l.exports,m,p,J,B)}return J[u].exports}for(var e="function"==typeof require&&require,n=0;n<B.length;n++)w(B[n]);return w}({1:[function(p,J,B){var m=p("./utils"),w=p("./support");B.encode=function(e){for(var n=[],u,t,l,x,d=0,h=e.length,v,E="string"!==m.getTypeOf(e);d<e.length;)v=h-d,E?(u=e[d++],t=d<h?e[d++]:0,l=d<h?e[d++]:0):(u=e.charCodeAt(d++),t=d<h?e.charCodeAt(d++):0,l=d<h?e.charCodeAt(d++):0),x=u>>2,u=(u&3)<<4|
t>>4,t=1<v?(t&15)<<2|l>>6:64,l=2<v?l&63:64,n.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(x)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(u)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(t)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l));return n.join("")};B.decode=function(e){var n=0,u=0;if("data:"===e.substr(0,5))throw Error("Invalid base64 input, it looks like a data url.");
e=e.replace(/[^A-Za-z0-9\+\/=]/g,"");var t=3*e.length/4;"="===e.charAt(e.length-1)&&t--;"="===e.charAt(e.length-2)&&t--;if(0!==t%1)throw Error("Invalid base64 input, bad content length.");var l;for(l=w.uint8array?new Uint8Array(t|0):Array(t|0);n<e.length;){var x="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(n++));var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(n++));t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(n++));
var h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(n++));x=x<<2|d>>4;d=(d&15)<<4|t>>2;var v=(t&3)<<6|h;l[u++]=x;64!==t&&(l[u++]=d);64!==h&&(l[u++]=v)}return l}},{"./support":30,"./utils":32}],2:[function(p,J,B){function m(t,l,x,d,h){this.compressedSize=t;this.uncompressedSize=l;this.crc32=x;this.compression=d;this.compressedContent=h}var w=p("./external"),e=p("./stream/DataWorker"),n=p("./stream/DataLengthProbe"),u=p("./stream/Crc32Probe");n=p("./stream/DataLengthProbe");
m.prototype={getContentWorker:function(){var t=(new e(w.Promise.resolve(this.compressedContent))).pipe(this.compression.uncompressWorker()).pipe(new n("data_length")),l=this;t.on("end",function(){if(this.streamInfo.data_length!==l.uncompressedSize)throw Error("Bug : uncompressed data size mismatch");});return t},getCompressedWorker:function(){return(new e(w.Promise.resolve(this.compressedContent))).withStreamInfo("compressedSize",this.compressedSize).withStreamInfo("uncompressedSize",this.uncompressedSize).withStreamInfo("crc32",
this.crc32).withStreamInfo("compression",this.compression)}};m.createWorkerFrom=function(t,l,x){return t.pipe(new u).pipe(new n("uncompressedSize")).pipe(l.compressWorker(x)).pipe(new n("compressedSize")).withStreamInfo("compression",l)};J.exports=m},{"./external":6,"./stream/Crc32Probe":25,"./stream/DataLengthProbe":26,"./stream/DataWorker":27}],3:[function(p,J,B){var m=p("./stream/GenericWorker");B.STORE={magic:"\x00\x00",compressWorker:function(w){return new m("STORE compression")},uncompressWorker:function(){return new m("STORE decompression")}};
B.DEFLATE=p("./flate")},{"./flate":7,"./stream/GenericWorker":28}],4:[function(p,J,B){var m=p("./utils"),w=function(){for(var e,n=[],u=0;256>u;u++){e=u;for(var t=0;8>t;t++)e=e&1?3988292384^e>>>1:e>>>1;n[u]=e}return n}();J.exports=function(e,n){if("undefined"===typeof e||!e.length)return 0;if("string"!==m.getTypeOf(e)){var u=0+e.length;var t=(n|0)^-1;for(var l=0;l<u;l++)t=t>>>8^w[(t^e[l])&255];return t^-1}u=0+e.length;t=(n|0)^-1;for(l=0;l<u;l++)t=t>>>8^w[(t^e.charCodeAt(l))&255];return t^-1}},{"./utils":32}],
5:[function(p,J,B){B.base64=!1;B.binary=!1;B.dir=!1;B.createFolders=!0;B.date=null;B.compression=null;B.compressionOptions=null;B.comment=null;B.unixPermissions=null;B.dosPermissions=null},{}],6:[function(p,J,B){p="undefined"!==typeof Promise?Promise:p("lie");J.exports={Promise:p}},{lie:37}],7:[function(p,J,B){function m(t,l){n.call(this,"FlateWorker/"+t);this._pako=null;this._pakoAction=t;this._pakoOptions=l;this.meta={}}J="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==
typeof Uint32Array;var w=p("pako"),e=p("./utils"),n=p("./stream/GenericWorker"),u=J?"uint8array":"array";B.magic="\b\x00";e.inherits(m,n);m.prototype.processChunk=function(t){this.meta=t.meta;null===this._pako&&this._createPako();this._pako.push(e.transformTo(u,t.data),!1)};m.prototype.flush=function(){n.prototype.flush.call(this);null===this._pako&&this._createPako();this._pako.push([],!0)};m.prototype.cleanUp=function(){n.prototype.cleanUp.call(this);this._pako=null};m.prototype._createPako=function(){this._pako=
new w[this._pakoAction]({raw:!0,level:this._pakoOptions.level||-1});var t=this;this._pako.onData=function(l){t.push({data:l,meta:t.meta})}};B.compressWorker=function(t){return new m("Deflate",t)};B.uncompressWorker=function(){return new m("Inflate",{})}},{"./stream/GenericWorker":28,"./utils":32,pako:38}],8:[function(p,J,B){function m(d,h,v,E){e.call(this,"ZipFileWorker");this.bytesWritten=0;this.zipComment=h;this.zipPlatform=v;this.encodeFileName=E;this.streamFiles=d;this.accumulate=!1;this.contentBuffer=
[];this.dirRecords=[];this.entriesCount=this.currentSourceOffset=0;this.currentFile=null;this._sources=[]}var w=p("../utils"),e=p("../stream/GenericWorker"),n=p("../utf8"),u=p("../crc32"),t=p("../signature"),l=function(d,h){var v="",E;for(E=0;E<h;E++)v+=String.fromCharCode(d&255),d>>>=8;return v},x=function(d,h,v,E,q,k){var r=d.file,g=d.compression,D=k!==n.utf8encode,F=w.transformTo("string",k(r.name)),H=w.transformTo("string",n.utf8encode(r.name)),L=r.comment;k=w.transformTo("string",k(L));var c=
w.transformTo("string",n.utf8encode(L)),S=H.length!==r.name.length,M=c.length!==L.length;L="";var a=r.dir;var A=r.date,f=0,z=0,y=0;if(!h||v)f=d.crc32,z=d.compressedSize,y=d.uncompressedSize;d=0;h&&(d|=8);D||!S&&!M||(d|=2048);h=0;a&&(h|=16);"UNIX"===q?(q=798,(D=r=r.unixPermissions)||(D=a?16893:33204),h|=(D&65535)<<16):(q=20,h|=(r.dosPermissions||0)&63);r=A.getUTCHours();r=r<<6|A.getUTCMinutes();r=r<<5|A.getUTCSeconds()/2;a=A.getUTCFullYear()-1980;a=a<<4|A.getUTCMonth()+1;a=a<<5|A.getUTCDate();S&&(H=
l(1,1)+l(u(F),4)+H,L+="up"+l(H.length,2)+H);M&&(H=l(1,1)+l(u(k),4)+c,L+="uc"+l(H.length,2)+H);H="\n\x00"+l(d,2);H+=g.magic;H+=l(r,2);H+=l(a,2);H+=l(f,4);H+=l(z,4);H+=l(y,4);H+=l(F.length,2);H+=l(L.length,2);g=t.LOCAL_FILE_HEADER+H+F+L;E=t.CENTRAL_FILE_HEADER+l(q,2)+H+l(k.length,2)+"\x00\x00\x00\x00"+l(h,4)+l(E,4)+F+L+k;return{fileRecord:g,dirRecord:E}};w.inherits(m,e);m.prototype.push=function(d){var h=d.meta.percent||0,v=this.entriesCount,E=this._sources.length;this.accumulate?this.contentBuffer.push(d):
(this.bytesWritten+=d.data.length,e.prototype.push.call(this,{data:d.data,meta:{currentFile:this.currentFile,percent:v?(h+100*(v-E-1))/v:100}}))};m.prototype.openedSource=function(d){this.currentSourceOffset=this.bytesWritten;this.currentFile=d.file.name;var h=this.streamFiles&&!d.file.dir;h?(d=x(d,h,!1,this.currentSourceOffset,this.zipPlatform,this.encodeFileName),this.push({data:d.fileRecord,meta:{percent:0}})):this.accumulate=!0};m.prototype.closedSource=function(d){this.accumulate=!1;var h=this.streamFiles&&
!d.file.dir,v=x(d,h,!0,this.currentSourceOffset,this.zipPlatform,this.encodeFileName);this.dirRecords.push(v.dirRecord);if(h)h=this.push,d=t.DATA_DESCRIPTOR+l(d.crc32,4)+l(d.compressedSize,4)+l(d.uncompressedSize,4),h.call(this,{data:d,meta:{percent:100}});else for(this.push({data:v.fileRecord,meta:{percent:0}});this.contentBuffer.length;)this.push(this.contentBuffer.shift());this.currentFile=null};m.prototype.flush=function(){for(var d=this.bytesWritten,h=0;h<this.dirRecords.length;h++)this.push({data:this.dirRecords[h],
meta:{percent:100}});h=this.dirRecords.length;var v=this.bytesWritten-d,E=w.transformTo("string",(0,this.encodeFileName)(this.zipComment));d=t.CENTRAL_DIRECTORY_END+"\x00\x00\x00\x00"+l(h,2)+l(h,2)+l(v,4)+l(d,4)+l(E.length,2)+E;this.push({data:d,meta:{percent:100}})};m.prototype.prepareNextSource=function(){this.previous=this._sources.shift();this.openedSource(this.previous.streamInfo);this.isPaused?this.previous.pause():this.previous.resume()};m.prototype.registerPrevious=function(d){this._sources.push(d);
var h=this;d.on("data",function(v){h.processChunk(v)});d.on("end",function(){h.closedSource(h.previous.streamInfo);h._sources.length?h.prepareNextSource():h.end()});d.on("error",function(v){h.error(v)});return this};m.prototype.resume=function(){if(!e.prototype.resume.call(this))return!1;if(!this.previous&&this._sources.length)return this.prepareNextSource(),!0;if(!this.previous&&!this._sources.length&&!this.generatedError)return this.end(),!0};m.prototype.error=function(d){var h=this._sources;if(!e.prototype.error.call(this,
d))return!1;for(var v=0;v<h.length;v++)try{h[v].error(d)}catch(E){}return!0};m.prototype.lock=function(){e.prototype.lock.call(this);for(var d=this._sources,h=0;h<d.length;h++)d[h].lock()};J.exports=m},{"../crc32":4,"../signature":23,"../stream/GenericWorker":28,"../utf8":31,"../utils":32}],9:[function(p,J,B){var m=p("../compressions"),w=p("./ZipFileWorker");B.generateWorker=function(e,n,u){var t=new w(n.streamFiles,u,n.platform,n.encodeFileName),l=0;try{e.forEach(function(x,d){l++;var h=d.options.compression||
n.compression,v=m[h];if(!v)throw Error(h+" is not a valid compression method !");h=d.dir;var E=d.date;d._compressWorker(v,d.options.compressionOptions||n.compressionOptions||{}).withStreamInfo("file",{name:x,dir:h,date:E,comment:d.comment||"",unixPermissions:d.unixPermissions,dosPermissions:d.dosPermissions}).pipe(t)}),t.entriesCount=l}catch(x){t.error(x)}return t}},{"../compressions":3,"./ZipFileWorker":8}],10:[function(p,J,B){function m(){if(!(this instanceof m))return new m;if(arguments.length)throw Error("The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.");
this.files={};this.comment=null;this.root="";this.clone=function(){var w=new m,e;for(e in this)"function"!==typeof this[e]&&(w[e]=this[e]);return w}}m.prototype=p("./object");m.prototype.loadAsync=p("./load");m.support=p("./support");m.defaults=p("./defaults");m.version="3.5.0";m.loadAsync=function(w,e){return(new m).loadAsync(w,e)};m.external=p("./external");J.exports=m},{"./defaults":5,"./external":6,"./load":11,"./object":15,"./support":30}],11:[function(p,J,B){function m(x){return new e.Promise(function(d,
h){var v=x.decompressed.getContentWorker().pipe(new t);v.on("error",function(E){h(E)}).on("end",function(){v.streamInfo.crc32!==x.decompressed.crc32?h(Error("Corrupted zip : CRC32 mismatch")):d()}).resume()})}var w=p("./utils"),e=p("./external"),n=p("./utf8");w=p("./utils");var u=p("./zipEntries"),t=p("./stream/Crc32Probe"),l=p("./nodejsUtils");J.exports=function(x,d){var h=this;d=w.extend(d||{},{base64:!1,checkCRC32:!1,optimizedBinaryString:!1,createFolders:!1,decodeFileName:n.utf8decode});return l.isNode&&
l.isStream(x)?e.Promise.reject(Error("JSZip can't accept a stream when loading a zip file.")):w.prepareContent("the loaded zip file",x,!0,d.optimizedBinaryString,d.base64).then(function(v){var E=new u(d);E.load(v);return E}).then(function(v){var E=[e.Promise.resolve(v)];v=v.files;if(d.checkCRC32)for(var q=0;q<v.length;q++)E.push(m(v[q]));return e.Promise.all(E)}).then(function(v){v=v.shift();for(var E=v.files,q=0;q<E.length;q++){var k=E[q];h.file(k.fileNameStr,k.decompressed,{binary:!0,optimizedBinaryString:!0,
date:k.date,dir:k.dir,comment:k.fileCommentStr.length?k.fileCommentStr:null,unixPermissions:k.unixPermissions,dosPermissions:k.dosPermissions,createFolders:d.createFolders})}v.zipComment.length&&(h.comment=v.zipComment);return h})}},{"./external":6,"./nodejsUtils":14,"./stream/Crc32Probe":25,"./utf8":31,"./utils":32,"./zipEntries":33}],12:[function(p,J,B){function m(e,n){w.call(this,"Nodejs stream input adapter for "+e);this._upstreamEnded=!1;this._bindStream(n)}B=p("../utils");var w=p("../stream/GenericWorker");
B.inherits(m,w);m.prototype._bindStream=function(e){var n=this;this._stream=e;e.pause();e.on("data",function(u){n.push({data:u,meta:{percent:0}})}).on("error",function(u){n.isPaused?this.generatedError=u:n.error(u)}).on("end",function(){n.isPaused?n._upstreamEnded=!0:n.end()})};m.prototype.pause=function(){if(!w.prototype.pause.call(this))return!1;this._stream.pause();return!0};m.prototype.resume=function(){if(!w.prototype.resume.call(this))return!1;this._upstreamEnded?this.end():this._stream.resume();
return!0};J.exports=m},{"../stream/GenericWorker":28,"../utils":32}],13:[function(p,J,B){function m(e,n,u){w.call(this,n);this._helper=e;var t=this;e.on("data",function(l,x){t.push(l)||t._helper.pause();u&&u(x)}).on("error",function(l){t.emit("error",l)}).on("end",function(){t.push(null)})}var w=p("readable-stream").Readable;p("../utils").inherits(m,w);m.prototype._read=function(){this._helper.resume()};J.exports=m},{"../utils":32,"readable-stream":16}],14:[function(p,J,B){J.exports={isNode:"undefined"!==
typeof Buffer,newBufferFrom:function(m,w){if(Buffer.from&&Buffer.from!==Uint8Array.from)return Buffer.from(m,w);if("number"===typeof m)throw Error('The "data" argument must not be a number');return new Buffer(m,w)},allocBuffer:function(m){if(Buffer.alloc)return Buffer.alloc(m);m=new Buffer(m);m.fill(0);return m},isBuffer:function(m){return Buffer.isBuffer(m)},isStream:function(m){return m&&"function"===typeof m.on&&"function"===typeof m.pause&&"function"===typeof m.resume}}},{}],15:[function(p,J,
B){var m=p("./utf8"),w=p("./utils"),e=p("./stream/GenericWorker"),n=p("./stream/StreamHelper"),u=p("./defaults"),t=p("./compressedObject"),l=p("./zipObject"),x=p("./generate"),d=p("./nodejsUtils"),h=p("./nodejs/NodejsStreamInputAdapter"),v=function(k,r,g){var D=w.getTypeOf(r),F=w.extend(g||{},u);F.date=F.date||new Date;null!==F.compression&&(F.compression=F.compression.toUpperCase());"string"===typeof F.unixPermissions&&(F.unixPermissions=parseInt(F.unixPermissions,8));F.unixPermissions&&F.unixPermissions&
16384&&(F.dir=!0);F.dosPermissions&&F.dosPermissions&16&&(F.dir=!0);F.dir&&(k=E(k));var H;if(H=F.createFolders){var L=k;"/"===L.slice(-1)&&(L=L.substring(0,L.length-1));H=L.lastIndexOf("/");H=L=0<H?L.substring(0,H):""}H&&q.call(this,L,!0);D="string"===D&&!1===F.binary&&!1===F.base64;g&&"undefined"!==typeof g.binary||(F.binary=!D);if(r instanceof t&&0===r.uncompressedSize||F.dir||!r||0===r.length)F.base64=!1,F.binary=!0,r="",F.compression="STORE";r=r instanceof t||r instanceof e?r:d.isNode&&d.isStream(r)?
new h(k,r):w.prepareContent(k,r,F.binary,F.optimizedBinaryString,F.base64);F=new l(k,r,F);this.files[k]=F},E=function(k){"/"!==k.slice(-1)&&(k+="/");return k},q=function(k,r){r="undefined"!==typeof r?r:u.createFolders;k=E(k);this.files[k]||v.call(this,k,null,{dir:!0,createFolders:r});return this.files[k]};J.exports={load:function(){throw Error("This method has been removed in JSZip 3.0, please check the upgrade guide.");},forEach:function(k){var r,g;for(r in this.files)if(this.files.hasOwnProperty(r)){var D=
this.files[r];(g=r.slice(this.root.length,r.length))&&r.slice(0,this.root.length)===this.root&&k(g,D)}},filter:function(k){var r=[];this.forEach(function(g,D){k(g,D)&&r.push(D)});return r},file:function(k,r,g){if(1===arguments.length){if("[object RegExp]"===Object.prototype.toString.call(k)){var D=k;return this.filter(function(H,L){return!L.dir&&D.test(H)})}var F=this.files[this.root+k];return F&&!F.dir?F:null}k=this.root+k;v.call(this,k,r,g);return this},folder:function(k){if(!k)return this;if("[object RegExp]"===
Object.prototype.toString.call(k))return this.filter(function(D,F){return F.dir&&k.test(D)});var r=q.call(this,this.root+k),g=this.clone();g.root=r.name;return g},remove:function(k){k=this.root+k;var r=this.files[k];r||("/"!==k.slice(-1)&&(k+="/"),r=this.files[k]);if(r&&!r.dir)delete this.files[k];else{r=this.filter(function(D,F){return F.name.slice(0,k.length)===k});for(var g=0;g<r.length;g++)delete this.files[r[g].name]}return this},generate:function(k){throw Error("This method has been removed in JSZip 3.0, please check the upgrade guide.");
},generateInternalStream:function(k){var r={};try{r=w.extend(k||{},{streamFiles:!1,compression:"STORE",compressionOptions:null,type:"",platform:"DOS",comment:null,mimeType:"application/zip",encodeFileName:m.utf8encode});r.type=r.type.toLowerCase();r.compression=r.compression.toUpperCase();"binarystring"===r.type&&(r.type="string");if(!r.type)throw Error("No output type specified.");w.checkSupport(r.type);if("darwin"===r.platform||"freebsd"===r.platform||"linux"===r.platform||"sunos"===r.platform)r.platform=
"UNIX";"win32"===r.platform&&(r.platform="DOS");var g=x.generateWorker(this,r,r.comment||this.comment||"")}catch(D){g=new e("error"),g.error(D)}return new n(g,r.type||"string",r.mimeType)},generateAsync:function(k,r){return this.generateInternalStream(k).accumulate(r)},generateNodeStream:function(k,r){k=k||{};k.type||(k.type="nodebuffer");return this.generateInternalStream(k).toNodejsStream(r)}}},{"./compressedObject":2,"./defaults":5,"./generate":9,"./nodejs/NodejsStreamInputAdapter":12,"./nodejsUtils":14,
"./stream/GenericWorker":28,"./stream/StreamHelper":29,"./utf8":31,"./utils":32,"./zipObject":35}],16:[function(p,J,B){J.exports=p("stream")},{stream:void 0}],17:[function(p,J,B){function m(e){w.call(this,e);for(var n=0;n<this.data.length;n++)e[n]&=255}var w=p("./DataReader");p("../utils").inherits(m,w);m.prototype.byteAt=function(e){return this.data[this.zero+e]};m.prototype.lastIndexOfSignature=function(e){var n=e.charCodeAt(0),u=e.charCodeAt(1),t=e.charCodeAt(2);e=e.charCodeAt(3);for(var l=this.length-
4;0<=l;--l)if(this.data[l]===n&&this.data[l+1]===u&&this.data[l+2]===t&&this.data[l+3]===e)return l-this.zero;return-1};m.prototype.readAndCheckSignature=function(e){var n=e.charCodeAt(0),u=e.charCodeAt(1),t=e.charCodeAt(2);e=e.charCodeAt(3);var l=this.readData(4);return n===l[0]&&u===l[1]&&t===l[2]&&e===l[3]};m.prototype.readData=function(e){this.checkOffset(e);if(0===e)return[];var n=this.data.slice(this.zero+this.index,this.zero+this.index+e);this.index+=e;return n};J.exports=m},{"../utils":32,
"./DataReader":18}],18:[function(p,J,B){function m(e){this.data=e;this.length=e.length;this.zero=this.index=0}var w=p("../utils");m.prototype={checkOffset:function(e){this.checkIndex(this.index+e)},checkIndex:function(e){if(this.length<this.zero+e||0>e)throw Error("End of data reached (data length = "+this.length+", asked index = "+e+"). Corrupted zip ?");},setIndex:function(e){this.checkIndex(e);this.index=e},skip:function(e){this.setIndex(this.index+e)},byteAt:function(e){},readInt:function(e){var n=
0,u;this.checkOffset(e);for(u=this.index+e-1;u>=this.index;u--)n=(n<<8)+this.byteAt(u);this.index+=e;return n},readString:function(e){return w.transformTo("string",this.readData(e))},readData:function(e){},lastIndexOfSignature:function(e){},readAndCheckSignature:function(e){},readDate:function(){var e=this.readInt(4);return new Date(Date.UTC((e>>25&127)+1980,(e>>21&15)-1,e>>16&31,e>>11&31,e>>5&63,(e&31)<<1))}};J.exports=m},{"../utils":32}],19:[function(p,J,B){function m(e){w.call(this,e)}var w=p("./Uint8ArrayReader");
p("../utils").inherits(m,w);m.prototype.readData=function(e){this.checkOffset(e);var n=this.data.slice(this.zero+this.index,this.zero+this.index+e);this.index+=e;return n};J.exports=m},{"../utils":32,"./Uint8ArrayReader":21}],20:[function(p,J,B){function m(e){w.call(this,e)}var w=p("./DataReader");p("../utils").inherits(m,w);m.prototype.byteAt=function(e){return this.data.charCodeAt(this.zero+e)};m.prototype.lastIndexOfSignature=function(e){return this.data.lastIndexOf(e)-this.zero};m.prototype.readAndCheckSignature=
function(e){var n=this.readData(4);return e===n};m.prototype.readData=function(e){this.checkOffset(e);var n=this.data.slice(this.zero+this.index,this.zero+this.index+e);this.index+=e;return n};J.exports=m},{"../utils":32,"./DataReader":18}],21:[function(p,J,B){function m(e){w.call(this,e)}var w=p("./ArrayReader");p("../utils").inherits(m,w);m.prototype.readData=function(e){this.checkOffset(e);if(0===e)return new Uint8Array(0);var n=this.data.subarray(this.zero+this.index,this.zero+this.index+e);this.index+=
e;return n};J.exports=m},{"../utils":32,"./ArrayReader":17}],22:[function(p,J,B){var m=p("../utils"),w=p("../support"),e=p("./ArrayReader"),n=p("./StringReader"),u=p("./NodeBufferReader"),t=p("./Uint8ArrayReader");J.exports=function(l){var x=m.getTypeOf(l);m.checkSupport(x);return"string"!==x||w.uint8array?"nodebuffer"===x?new u(l):w.uint8array?new t(m.transformTo("uint8array",l)):new e(m.transformTo("array",l)):new n(l)}},{"../support":30,"../utils":32,"./ArrayReader":17,"./NodeBufferReader":19,
"./StringReader":20,"./Uint8ArrayReader":21}],23:[function(p,J,B){B.LOCAL_FILE_HEADER="PK\u0003\u0004";B.CENTRAL_FILE_HEADER="PK\u0001\u0002";B.CENTRAL_DIRECTORY_END="PK\u0005\u0006";B.ZIP64_CENTRAL_DIRECTORY_LOCATOR="PK\u0006\u0007";B.ZIP64_CENTRAL_DIRECTORY_END="PK\u0006\u0006";B.DATA_DESCRIPTOR="PK\u0007\b"},{}],24:[function(p,J,B){function m(n){w.call(this,"ConvertWorker to "+n);this.destType=n}var w=p("./GenericWorker"),e=p("../utils");e.inherits(m,w);m.prototype.processChunk=function(n){this.push({data:e.transformTo(this.destType,
n.data),meta:n.meta})};J.exports=m},{"../utils":32,"./GenericWorker":28}],25:[function(p,J,B){function m(){w.call(this,"Crc32Probe");this.withStreamInfo("crc32",0)}var w=p("./GenericWorker"),e=p("../crc32");p("../utils").inherits(m,w);m.prototype.processChunk=function(n){this.streamInfo.crc32=e(n.data,this.streamInfo.crc32||0);this.push(n)};J.exports=m},{"../crc32":4,"../utils":32,"./GenericWorker":28}],26:[function(p,J,B){function m(e){w.call(this,"DataLengthProbe for "+e);this.propName=e;this.withStreamInfo(e,
0)}B=p("../utils");var w=p("./GenericWorker");B.inherits(m,w);m.prototype.processChunk=function(e){e&&(this.streamInfo[this.propName]=(this.streamInfo[this.propName]||0)+e.data.length);w.prototype.processChunk.call(this,e)};J.exports=m},{"../utils":32,"./GenericWorker":28}],27:[function(p,J,B){function m(n){e.call(this,"DataWorker");var u=this;this.dataIsReady=!1;this.max=this.index=0;this.data=null;this.type="";this._tickScheduled=!1;n.then(function(t){u.dataIsReady=!0;u.data=t;u.max=t&&t.length||
0;u.type=w.getTypeOf(t);u.isPaused||u._tickAndRepeat()},function(t){u.error(t)})}var w=p("../utils"),e=p("./GenericWorker");w.inherits(m,e);m.prototype.cleanUp=function(){e.prototype.cleanUp.call(this);this.data=null};m.prototype.resume=function(){if(!e.prototype.resume.call(this))return!1;!this._tickScheduled&&this.dataIsReady&&(this._tickScheduled=!0,w.delay(this._tickAndRepeat,[],this));return!0};m.prototype._tickAndRepeat=function(){this._tickScheduled=!1;this.isPaused||this.isFinished||(this._tick(),
this.isFinished||(w.delay(this._tickAndRepeat,[],this),this._tickScheduled=!0))};m.prototype._tick=function(){if(this.isPaused||this.isFinished)return!1;var n=null,u=Math.min(this.max,this.index+16384);if(this.index>=this.max)return this.end();switch(this.type){case "string":n=this.data.substring(this.index,u);break;case "uint8array":n=this.data.subarray(this.index,u);break;case "array":case "nodebuffer":n=this.data.slice(this.index,u)}this.index=u;return this.push({data:n,meta:{percent:this.max?
this.index/this.max*100:0}})};J.exports=m},{"../utils":32,"./GenericWorker":28}],28:[function(p,J,B){function m(w){this.name=w||"default";this.streamInfo={};this.generatedError=null;this.extraStreamInfo={};this.isPaused=!0;this.isLocked=this.isFinished=!1;this._listeners={data:[],end:[],error:[]};this.previous=null}m.prototype={push:function(w){this.emit("data",w)},end:function(){if(this.isFinished)return!1;this.flush();try{this.emit("end"),this.cleanUp(),this.isFinished=!0}catch(w){this.emit("error",
w)}return!0},error:function(w){if(this.isFinished)return!1;this.isPaused?this.generatedError=w:(this.isFinished=!0,this.emit("error",w),this.previous&&this.previous.error(w),this.cleanUp());return!0},on:function(w,e){this._listeners[w].push(e);return this},cleanUp:function(){this.streamInfo=this.generatedError=this.extraStreamInfo=null;this._listeners=[]},emit:function(w,e){if(this._listeners[w])for(var n=0;n<this._listeners[w].length;n++)this._listeners[w][n].call(this,e)},pipe:function(w){return w.registerPrevious(this)},
registerPrevious:function(w){if(this.isLocked)throw Error("The stream '"+this+"' has already been used.");this.streamInfo=w.streamInfo;this.mergeStreamInfo();this.previous=w;var e=this;w.on("data",function(n){e.processChunk(n)});w.on("end",function(){e.end()});w.on("error",function(n){e.error(n)});return this},pause:function(){if(this.isPaused||this.isFinished)return!1;this.isPaused=!0;this.previous&&this.previous.pause();return!0},resume:function(){if(!this.isPaused||this.isFinished)return!1;var w=
this.isPaused=!1;this.generatedError&&(this.error(this.generatedError),w=!0);this.previous&&this.previous.resume();return!w},flush:function(){},processChunk:function(w){this.push(w)},withStreamInfo:function(w,e){this.extraStreamInfo[w]=e;this.mergeStreamInfo();return this},mergeStreamInfo:function(){for(var w in this.extraStreamInfo)this.extraStreamInfo.hasOwnProperty(w)&&(this.streamInfo[w]=this.extraStreamInfo[w])},lock:function(){if(this.isLocked)throw Error("The stream '"+this+"' has already been used.");
this.isLocked=!0;this.previous&&this.previous.lock()},toString:function(){var w="Worker "+this.name;return this.previous?this.previous+" -> "+w:w}};J.exports=m},{}],29:[function(p,J,B){function m(h,v){var E,q=0,k;for(E=k=0;E<v.length;E++)k+=v[E].length;switch(h){case "string":return v.join("");case "array":return Array.prototype.concat.apply([],v);case "uint8array":k=new Uint8Array(k);for(E=0;E<v.length;E++)k.set(v[E],q),q+=v[E].length;return k;case "nodebuffer":return Buffer.concat(v);default:throw Error("concat : unsupported type '"+
h+"'");}}function w(h,v){return new x.Promise(function(E,q){var k=[],r=h._internalType,g=h._outputType,D=h._mimeType;h.on("data",function(F,H){k.push(F);v&&v(H)}).on("error",function(F){k=[];q(F)}).on("end",function(){try{a:{var F=m(r,k);switch(g){case "blob":var H=n.newBlob(n.transformTo("arraybuffer",F),D);break a;case "base64":H=l.encode(F);break a;default:H=n.transformTo(g,F)}}E(H)}catch(L){q(L)}k=[]}).resume()})}function e(h,v,E){var q=v;switch(v){case "blob":case "arraybuffer":q="uint8array";
break;case "base64":q="string"}try{this._internalType=q,this._outputType=v,this._mimeType=E,n.checkSupport(q),this._worker=h.pipe(new u(q)),h.lock()}catch(k){this._worker=new t("error"),this._worker.error(k)}}var n=p("../utils"),u=p("./ConvertWorker"),t=p("./GenericWorker"),l=p("../base64");B=p("../support");var x=p("../external"),d=null;if(B.nodestream)try{d=p("../nodejs/NodejsStreamOutputAdapter")}catch(h){}e.prototype={accumulate:function(h){return w(this,h)},on:function(h,v){var E=this;if("data"===
h)this._worker.on(h,function(q){v.call(E,q.data,q.meta)});else this._worker.on(h,function(){n.delay(v,arguments,E)});return this},resume:function(){n.delay(this._worker.resume,[],this._worker);return this},pause:function(){this._worker.pause();return this},toNodejsStream:function(h){n.checkSupport("nodestream");if("nodebuffer"!==this._outputType)throw Error(this._outputType+" is not supported by this method");return new d(this,{objectMode:"nodebuffer"!==this._outputType},h)}};J.exports=e},{"../base64":1,
"../external":6,"../nodejs/NodejsStreamOutputAdapter":13,"../support":30,"../utils":32,"./ConvertWorker":24,"./GenericWorker":28}],30:[function(p,J,B){B.base64=!0;B.array=!0;B.string=!0;B.arraybuffer="undefined"!==typeof ArrayBuffer&&"undefined"!==typeof Uint8Array;B.nodebuffer="undefined"!==typeof Buffer;B.uint8array="undefined"!==typeof Uint8Array;if("undefined"===typeof ArrayBuffer)B.blob=!1;else{J=new ArrayBuffer(0);try{B.blob=0===(new Blob([J],{type:"application/zip"})).size}catch(w){try{var m=
new (self.BlobBuilder||self.WebKitBlobBuilder||self.MozBlobBuilder||self.MSBlobBuilder);m.append(J);B.blob=0===m.getBlob("application/zip").size}catch(e){B.blob=!1}}}try{B.nodestream=!!p("readable-stream").Readable}catch(w){B.nodestream=!1}},{"readable-stream":16}],31:[function(p,J,B){function m(){t.call(this,"utf-8 decode");this.leftOver=null}function w(){t.call(this,"utf-8 encode")}var e=p("./utils"),n=p("./support"),u=p("./nodejsUtils"),t=p("./stream/GenericWorker"),l=Array(256);for(p=0;256>p;p++)l[p]=
252<=p?6:248<=p?5:240<=p?4:224<=p?3:192<=p?2:1;l[254]=l[254]=1;B.utf8encode=function(x){if(n.nodebuffer)return u.newBufferFrom(x,"utf-8");var d,h,v=x.length,E=0;for(d=0;d<v;d++){var q=x.charCodeAt(d);if(55296===(q&64512)&&d+1<v){var k=x.charCodeAt(d+1);56320===(k&64512)&&(q=65536+(q-55296<<10)+(k-56320),d++)}E+=128>q?1:2048>q?2:65536>q?3:4}var r=n.uint8array?new Uint8Array(E):Array(E);for(d=h=0;h<E;d++)q=x.charCodeAt(d),55296===(q&64512)&&d+1<v&&(k=x.charCodeAt(d+1),56320===(k&64512)&&(q=65536+(q-
55296<<10)+(k-56320),d++)),128>q?r[h++]=q:(2048>q?r[h++]=192|q>>>6:(65536>q?r[h++]=224|q>>>12:(r[h++]=240|q>>>18,r[h++]=128|q>>>12&63),r[h++]=128|q>>>6&63),r[h++]=128|q&63);return r};B.utf8decode=function(x){if(n.nodebuffer)return e.transformTo("nodebuffer",x).toString("utf-8");x=e.transformTo(n.uint8array?"uint8array":"array",x);var d,h,v=x.length,E=Array(2*v);for(d=h=0;d<v;){var q=x[d++];if(128>q)E[h++]=q;else{var k=l[q];if(4<k)E[h++]=65533,d+=k-1;else{for(q&=2===k?31:3===k?15:7;1<k&&d<v;)q=q<<
6|x[d++]&63,k--;1<k?E[h++]=65533:65536>q?E[h++]=q:(q-=65536,E[h++]=55296|q>>10&1023,E[h++]=56320|q&1023)}}}E.length!==h&&(E.subarray?E=E.subarray(0,h):E.length=h);return e.applyFromCharCode(E)};e.inherits(m,t);m.prototype.processChunk=function(x){var d=e.transformTo(n.uint8array?"uint8array":"array",x.data);if(this.leftOver&&this.leftOver.length){if(n.uint8array){var h=d;d=new Uint8Array(h.length+this.leftOver.length);d.set(this.leftOver,0);d.set(h,this.leftOver.length)}else d=this.leftOver.concat(d);
this.leftOver=null}var v;h=d.length;h>d.length&&(h=d.length);for(v=h-1;0<=v&&128===(d[v]&192);)v--;h=0>v?h:0===v?h:v+l[d[v]]>h?v:h;v=d;h!==d.length&&(n.uint8array?(v=d.subarray(0,h),this.leftOver=d.subarray(h,d.length)):(v=d.slice(0,h),this.leftOver=d.slice(h,d.length)));this.push({data:B.utf8decode(v),meta:x.meta})};m.prototype.flush=function(){this.leftOver&&this.leftOver.length&&(this.push({data:B.utf8decode(this.leftOver),meta:{}}),this.leftOver=null)};B.Utf8DecodeWorker=m;e.inherits(w,t);w.prototype.processChunk=
function(x){this.push({data:B.utf8encode(x.data),meta:x.meta})};B.Utf8EncodeWorker=w},{"./nodejsUtils":14,"./stream/GenericWorker":28,"./support":30,"./utils":32}],32:[function(p,J,B){function m(k){return k}function w(k,r){for(var g=0;g<k.length;++g)r[g]=k.charCodeAt(g)&255;return r}function e(k){var r=65536,g=B.getTypeOf(k),D=!0;"uint8array"===g?D=E.applyCanBeUsed.uint8array:"nodebuffer"===g&&(D=E.applyCanBeUsed.nodebuffer);if(D)for(;1<r;)try{return E.stringifyByChunk(k,g,r)}catch(F){r=Math.floor(r/
2)}return E.stringifyByChar(k)}function n(k,r){for(var g=0;g<k.length;g++)r[g]=k[g];return r}var u=p("./support"),t=p("./base64"),l=p("./nodejsUtils"),x=p("set-immediate-shim"),d=p("./external");B.newBlob=function(k,r){B.checkSupport("blob");try{return new Blob([k],{type:r})}catch(D){try{var g=new (self.BlobBuilder||self.WebKitBlobBuilder||self.MozBlobBuilder||self.MSBlobBuilder);g.append(k);return g.getBlob(r)}catch(F){throw Error("Bug : can't construct the Blob.");}}};try{var h=u.uint8array&&1===
String.fromCharCode.apply(null,new Uint8Array(1)).length}catch(k){h=!1}p=h;try{var v=u.nodebuffer&&1===String.fromCharCode.apply(null,l.allocBuffer(1)).length}catch(k){v=!1}var E={stringifyByChunk:function(k,r,g){var D=[],F=0,H=k.length;if(H<=g)return String.fromCharCode.apply(null,k);for(;F<H;)"array"===r||"nodebuffer"===r?D.push(String.fromCharCode.apply(null,k.slice(F,Math.min(F+g,H)))):D.push(String.fromCharCode.apply(null,k.subarray(F,Math.min(F+g,H)))),F+=g;return D.join("")},stringifyByChar:function(k){for(var r=
"",g=0;g<k.length;g++)r+=String.fromCharCode(k[g]);return r},applyCanBeUsed:{uint8array:p,nodebuffer:v}};B.applyFromCharCode=e;var q={};q.string={string:m,array:function(k){return w(k,Array(k.length))},arraybuffer:function(k){return q.string.uint8array(k).buffer},uint8array:function(k){return w(k,new Uint8Array(k.length))},nodebuffer:function(k){return w(k,l.allocBuffer(k.length))}};q.array={string:e,array:m,arraybuffer:function(k){return(new Uint8Array(k)).buffer},uint8array:function(k){return new Uint8Array(k)},
nodebuffer:function(k){return l.newBufferFrom(k)}};q.arraybuffer={string:function(k){return e(new Uint8Array(k))},array:function(k){return n(new Uint8Array(k),Array(k.byteLength))},arraybuffer:m,uint8array:function(k){return new Uint8Array(k)},nodebuffer:function(k){return l.newBufferFrom(new Uint8Array(k))}};q.uint8array={string:e,array:function(k){return n(k,Array(k.length))},arraybuffer:function(k){return k.buffer},uint8array:m,nodebuffer:function(k){return l.newBufferFrom(k)}};q.nodebuffer={string:e,
array:function(k){return n(k,Array(k.length))},arraybuffer:function(k){return q.nodebuffer.uint8array(k).buffer},uint8array:function(k){return n(k,new Uint8Array(k.length))},nodebuffer:m};B.transformTo=function(k,r){r||(r="");if(!k)return r;B.checkSupport(k);var g=B.getTypeOf(r);return q[g][k](r)};B.getTypeOf=function(k){if("string"===typeof k)return"string";if("[object Array]"===Object.prototype.toString.call(k))return"array";if(u.nodebuffer&&l.isBuffer(k))return"nodebuffer";if(u.uint8array&&k instanceof
Uint8Array)return"uint8array";if(u.arraybuffer&&k instanceof ArrayBuffer)return"arraybuffer"};B.checkSupport=function(k){if(!u[k.toLowerCase()])throw Error(k+" is not supported by this platform");};B.MAX_VALUE_16BITS=65535;B.MAX_VALUE_32BITS=-1;B.pretty=function(k){var r="",g;for(g=0;g<(k||"").length;g++){var D=k.charCodeAt(g);r+="\\x"+(16>D?"0":"")+D.toString(16).toUpperCase()}return r};B.delay=function(k,r,g){x(function(){k.apply(g||null,r||[])})};B.inherits=function(k,r){var g=function(){};g.prototype=
r.prototype;k.prototype=new g};B.extend=function(){var k={},r,g;for(r=0;r<arguments.length;r++)for(g in arguments[r])arguments[r].hasOwnProperty(g)&&"undefined"===typeof k[g]&&(k[g]=arguments[r][g]);return k};B.prepareContent=function(k,r,g,D,F){return d.Promise.resolve(r).then(function(H){return u.blob&&(H instanceof Blob||-1!==["[object File]","[object Blob]"].indexOf(Object.prototype.toString.call(H)))&&"undefined"!==typeof FileReader?new d.Promise(function(L,c){var S=new FileReader;S.onload=function(M){L(M.target.result)};
S.onerror=function(M){c(M.target.error)};S.readAsArrayBuffer(H)}):H}).then(function(H){var L=B.getTypeOf(H);if(!L)return d.Promise.reject(Error("Can't read the data of '"+k+"'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?"));"arraybuffer"===L?H=B.transformTo("uint8array",H):"string"===L&&(F?H=t.decode(H):g&&!0!==D&&(L=u.uint8array?new Uint8Array(H.length):Array(H.length),H=w(H,L)));return H})}},{"./base64":1,"./external":6,"./nodejsUtils":14,"./support":30,"set-immediate-shim":54}],
33:[function(p,J,B){function m(l){this.files=[];this.loadOptions=l}var w=p("./reader/readerFor"),e=p("./utils"),n=p("./signature"),u=p("./zipEntry");p("./utf8");var t=p("./support");m.prototype={checkSignature:function(l){if(!this.reader.readAndCheckSignature(l)){this.reader.index-=4;var x=this.reader.readString(4);throw Error("Corrupted zip or bug: unexpected signature ("+e.pretty(x)+", expected "+e.pretty(l)+")");}},isSignature:function(l,x){var d=this.reader.index;this.reader.setIndex(l);var h=
this.reader.readString(4)===x;this.reader.setIndex(d);return h},readBlockEndOfCentral:function(){this.diskNumber=this.reader.readInt(2);this.diskWithCentralDirStart=this.reader.readInt(2);this.centralDirRecordsOnThisDisk=this.reader.readInt(2);this.centralDirRecords=this.reader.readInt(2);this.centralDirSize=this.reader.readInt(4);this.centralDirOffset=this.reader.readInt(4);this.zipCommentLength=this.reader.readInt(2);var l=this.reader.readData(this.zipCommentLength);l=e.transformTo(t.uint8array?
"uint8array":"array",l);this.zipComment=this.loadOptions.decodeFileName(l)},readBlockZip64EndOfCentral:function(){this.zip64EndOfCentralSize=this.reader.readInt(8);this.reader.skip(4);this.diskNumber=this.reader.readInt(4);this.diskWithCentralDirStart=this.reader.readInt(4);this.centralDirRecordsOnThisDisk=this.reader.readInt(8);this.centralDirRecords=this.reader.readInt(8);this.centralDirSize=this.reader.readInt(8);this.centralDirOffset=this.reader.readInt(8);this.zip64ExtensibleData={};for(var l=
this.zip64EndOfCentralSize-44,x,d,h;0<l;)x=this.reader.readInt(2),d=this.reader.readInt(4),h=this.reader.readData(d),this.zip64ExtensibleData[x]={id:x,length:d,value:h}},readBlockZip64EndOfCentralLocator:function(){this.diskWithZip64CentralDirStart=this.reader.readInt(4);this.relativeOffsetEndOfZip64CentralDir=this.reader.readInt(8);this.disksCount=this.reader.readInt(4);if(1<this.disksCount)throw Error("Multi-volumes zip are not supported");},readLocalFiles:function(){var l;for(l=0;l<this.files.length;l++){var x=
this.files[l];this.reader.setIndex(x.localHeaderOffset);this.checkSignature(n.LOCAL_FILE_HEADER);x.readLocalPart(this.reader);x.handleUTF8();x.processAttributes()}},readCentralDir:function(){for(this.reader.setIndex(this.centralDirOffset);this.reader.readAndCheckSignature(n.CENTRAL_FILE_HEADER);){var l=new u({zip64:this.zip64},this.loadOptions);l.readCentralPart(this.reader);this.files.push(l)}if(this.centralDirRecords!==this.files.length&&0!==this.centralDirRecords&&0===this.files.length)throw Error("Corrupted zip or bug: expected "+
this.centralDirRecords+" records in central dir, got "+this.files.length);},readEndOfCentral:function(){var l=this.reader.lastIndexOfSignature(n.CENTRAL_DIRECTORY_END);if(0>l){if(this.isSignature(0,n.LOCAL_FILE_HEADER))throw Error("Corrupted zip: can't find end of central directory");throw Error("Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html");}this.reader.setIndex(l);var x=l;this.checkSignature(n.CENTRAL_DIRECTORY_END);
this.readBlockEndOfCentral();if(this.diskNumber===e.MAX_VALUE_16BITS||this.diskWithCentralDirStart===e.MAX_VALUE_16BITS||this.centralDirRecordsOnThisDisk===e.MAX_VALUE_16BITS||this.centralDirRecords===e.MAX_VALUE_16BITS||this.centralDirSize===e.MAX_VALUE_32BITS||this.centralDirOffset===e.MAX_VALUE_32BITS){this.zip64=!0;l=this.reader.lastIndexOfSignature(n.ZIP64_CENTRAL_DIRECTORY_LOCATOR);if(0>l)throw Error("Corrupted zip: can't find the ZIP64 end of central directory locator");this.reader.setIndex(l);
this.checkSignature(n.ZIP64_CENTRAL_DIRECTORY_LOCATOR);this.readBlockZip64EndOfCentralLocator();if(!this.isSignature(this.relativeOffsetEndOfZip64CentralDir,n.ZIP64_CENTRAL_DIRECTORY_END)&&(this.relativeOffsetEndOfZip64CentralDir=this.reader.lastIndexOfSignature(n.ZIP64_CENTRAL_DIRECTORY_END),0>this.relativeOffsetEndOfZip64CentralDir))throw Error("Corrupted zip: can't find the ZIP64 end of central directory");this.reader.setIndex(this.relativeOffsetEndOfZip64CentralDir);this.checkSignature(n.ZIP64_CENTRAL_DIRECTORY_END);
this.readBlockZip64EndOfCentral()}l=this.centralDirOffset+this.centralDirSize;this.zip64&&(l=l+20+(12+this.zip64EndOfCentralSize));l=x-l;if(0<l)this.isSignature(x,n.CENTRAL_FILE_HEADER)||(this.reader.zero=l);else if(0>l)throw Error("Corrupted zip: missing "+Math.abs(l)+" bytes.");},prepareReader:function(l){this.reader=w(l)},load:function(l){this.prepareReader(l);this.readEndOfCentral();this.readCentralDir();this.readLocalFiles()}};J.exports=m},{"./reader/readerFor":22,"./signature":23,"./support":30,
"./utf8":31,"./utils":32,"./zipEntry":34}],34:[function(p,J,B){function m(d,h){this.options=d;this.loadOptions=h}var w=p("./reader/readerFor"),e=p("./utils"),n=p("./compressedObject"),u=p("./crc32"),t=p("./utf8"),l=p("./compressions"),x=p("./support");m.prototype={isEncrypted:function(){return 1===(this.bitFlag&1)},useUTF8:function(){return 2048===(this.bitFlag&2048)},readLocalPart:function(d){d.skip(22);this.fileNameLength=d.readInt(2);var h=d.readInt(2);this.fileName=d.readData(this.fileNameLength);
d.skip(h);if(-1===this.compressedSize||-1===this.uncompressedSize)throw Error("Bug or corrupted zip : didn't get enough information from the central directory (compressedSize === -1 || uncompressedSize === -1)");a:{h=this.compressionMethod;for(v in l)if(l.hasOwnProperty(v)&&l[v].magic===h){var v=l[v];break a}v=null}if(null===v)throw Error("Corrupted zip : compression "+e.pretty(this.compressionMethod)+" unknown (inner file : "+e.transformTo("string",this.fileName)+")");this.decompressed=new n(this.compressedSize,
this.uncompressedSize,this.crc32,v,d.readData(this.compressedSize))},readCentralPart:function(d){this.versionMadeBy=d.readInt(2);d.skip(2);this.bitFlag=d.readInt(2);this.compressionMethod=d.readString(2);this.date=d.readDate();this.crc32=d.readInt(4);this.compressedSize=d.readInt(4);this.uncompressedSize=d.readInt(4);var h=d.readInt(2);this.extraFieldsLength=d.readInt(2);this.fileCommentLength=d.readInt(2);this.diskNumberStart=d.readInt(2);this.internalFileAttributes=d.readInt(2);this.externalFileAttributes=
d.readInt(4);this.localHeaderOffset=d.readInt(4);if(this.isEncrypted())throw Error("Encrypted zip are not supported");d.skip(h);this.readExtraFields(d);this.parseZIP64ExtraField(d);this.fileComment=d.readData(this.fileCommentLength)},processAttributes:function(){this.dosPermissions=this.unixPermissions=null;var d=this.versionMadeBy>>8;this.dir=this.externalFileAttributes&16?!0:!1;0===d&&(this.dosPermissions=this.externalFileAttributes&63);3===d&&(this.unixPermissions=this.externalFileAttributes>>
16&65535);this.dir||"/"!==this.fileNameStr.slice(-1)||(this.dir=!0)},parseZIP64ExtraField:function(d){this.extraFields[1]&&(d=w(this.extraFields[1].value),this.uncompressedSize===e.MAX_VALUE_32BITS&&(this.uncompressedSize=d.readInt(8)),this.compressedSize===e.MAX_VALUE_32BITS&&(this.compressedSize=d.readInt(8)),this.localHeaderOffset===e.MAX_VALUE_32BITS&&(this.localHeaderOffset=d.readInt(8)),this.diskNumberStart===e.MAX_VALUE_32BITS&&(this.diskNumberStart=d.readInt(4)))},readExtraFields:function(d){var h=
d.index+this.extraFieldsLength;this.extraFields||(this.extraFields={});for(;d.index+4<h;){var v=d.readInt(2);var E=d.readInt(2);var q=d.readData(E);this.extraFields[v]={id:v,length:E,value:q}}d.setIndex(h)},handleUTF8:function(){var d=x.uint8array?"uint8array":"array";if(this.useUTF8())this.fileNameStr=t.utf8decode(this.fileName),this.fileCommentStr=t.utf8decode(this.fileComment);else{var h=this.findExtraFieldUnicodePath();null!==h?this.fileNameStr=h:(h=e.transformTo(d,this.fileName),this.fileNameStr=
this.loadOptions.decodeFileName(h));h=this.findExtraFieldUnicodeComment();null!==h?this.fileCommentStr=h:(d=e.transformTo(d,this.fileComment),this.fileCommentStr=this.loadOptions.decodeFileName(d))}},findExtraFieldUnicodePath:function(){var d=this.extraFields[28789];if(d){var h=w(d.value);return 1!==h.readInt(1)||u(this.fileName)!==h.readInt(4)?null:t.utf8decode(h.readData(d.length-5))}return null},findExtraFieldUnicodeComment:function(){var d=this.extraFields[25461];if(d){var h=w(d.value);return 1!==
h.readInt(1)||u(this.fileComment)!==h.readInt(4)?null:t.utf8decode(h.readData(d.length-5))}return null}};J.exports=m},{"./compressedObject":2,"./compressions":3,"./crc32":4,"./reader/readerFor":22,"./support":30,"./utf8":31,"./utils":32}],35:[function(p,J,B){var m=p("./stream/StreamHelper"),w=p("./stream/DataWorker"),e=p("./utf8"),n=p("./compressedObject"),u=p("./stream/GenericWorker");p=function(x,d,h){this.name=x;this.dir=h.dir;this.date=h.date;this.comment=h.comment;this.unixPermissions=h.unixPermissions;
this.dosPermissions=h.dosPermissions;this._data=d;this._dataBinary=h.binary;this.options={compression:h.compression,compressionOptions:h.compressionOptions}};p.prototype={internalStream:function(x){var d=null,h="string";try{if(!x)throw Error("No output type specified.");h=x.toLowerCase();x="string"===h||"text"===h;if("binarystring"===h||"text"===h)h="string";d=this._decompressWorker();var v=!this._dataBinary;v&&!x&&(d=d.pipe(new e.Utf8EncodeWorker));!v&&x&&(d=d.pipe(new e.Utf8DecodeWorker))}catch(E){d=
new u("error"),d.error(E)}return new m(d,h,"")},async:function(x,d){return this.internalStream(x).accumulate(d)},nodeStream:function(x,d){return this.internalStream(x||"nodebuffer").toNodejsStream(d)},_compressWorker:function(x,d){if(this._data instanceof n&&this._data.compression.magic===x.magic)return this._data.getCompressedWorker();var h=this._decompressWorker();this._dataBinary||(h=h.pipe(new e.Utf8EncodeWorker));return n.createWorkerFrom(h,x,d)},_decompressWorker:function(){return this._data instanceof
n?this._data.getContentWorker():this._data instanceof u?this._data:new w(this._data)}};B=["asText","asBinary","asNodeBuffer","asUint8Array","asArrayBuffer"];for(var t=function(){throw Error("This method has been removed in JSZip 3.0, please check the upgrade guide.");},l=0;l<B.length;l++)p.prototype[B[l]]=t;J.exports=p},{"./compressedObject":2,"./stream/DataWorker":27,"./stream/GenericWorker":28,"./stream/StreamHelper":29,"./utf8":31}],36:[function(p,J,B){(function(m){function w(){x=!0;for(var h,
v,E=d.length;E;){v=d;d=[];for(h=-1;++h<E;)v[h]();E=d.length}x=!1}var e=m.MutationObserver||m.WebKitMutationObserver;if(e){var n=0;e=new e(w);var u=m.document.createTextNode("");e.observe(u,{characterData:!0});var t=function(){u.data=n=++n%2}}else if(m.setImmediate||"undefined"===typeof m.MessageChannel)t="document"in m&&"onreadystatechange"in m.document.createElement("script")?function(){var h=m.document.createElement("script");h.onreadystatechange=function(){w();h.onreadystatechange=null;h.parentNode.removeChild(h);
h=null};m.document.documentElement.appendChild(h)}:function(){setTimeout(w,0)};else{var l=new m.MessageChannel;l.port1.onmessage=w;t=function(){l.port2.postMessage(0)}}var x,d=[];J.exports=function(h){1!==d.push(h)||x||t()}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{}],37:[function(p,J,B){function m(){}function w(q){if("function"!==typeof q)throw new TypeError("resolver must be a function");this.state=E;this.queue=[];this.outcome=
void 0;q!==m&&t(this,q)}function e(q,k,r){this.promise=q;"function"===typeof k&&(this.onFulfilled=k,this.callFulfilled=this.otherCallFulfilled);"function"===typeof r&&(this.onRejected=r,this.callRejected=this.otherCallRejected)}function n(q,k,r){x(function(){try{var g=k(r)}catch(D){return d.reject(q,D)}g===q?d.reject(q,new TypeError("Cannot resolve promise with itself")):d.resolve(q,g)})}function u(q){var k=q&&q.then;if(q&&("object"===typeof q||"function"===typeof q)&&"function"===typeof k)return function(){k.apply(q,
arguments)}}function t(q,k){function r(H){D||(D=!0,d.reject(q,H))}function g(H){D||(D=!0,d.resolve(q,H))}var D=!1,F=l(function(){k(g,r)});"error"===F.status&&r(F.value)}function l(q,k){var r={};try{r.value=q(k),r.status="success"}catch(g){r.status="error",r.value=g}return r}var x=p("immediate"),d={},h=["REJECTED"],v=["FULFILLED"],E=["PENDING"];J.exports=w;w.prototype["finally"]=function(q){if("function"!==typeof q)return this;var k=this.constructor;return this.then(function(r){return k.resolve(q()).then(function(){return r})},
function(r){return k.resolve(q()).then(function(){throw r;})})};w.prototype["catch"]=function(q){return this.then(null,q)};w.prototype.then=function(q,k){if("function"!==typeof q&&this.state===v||"function"!==typeof k&&this.state===h)return this;var r=new this.constructor(m);this.state!==E?n(r,this.state===v?q:k,this.outcome):this.queue.push(new e(r,q,k));return r};e.prototype.callFulfilled=function(q){d.resolve(this.promise,q)};e.prototype.otherCallFulfilled=function(q){n(this.promise,this.onFulfilled,
q)};e.prototype.callRejected=function(q){d.reject(this.promise,q)};e.prototype.otherCallRejected=function(q){n(this.promise,this.onRejected,q)};d.resolve=function(q,k){var r=l(u,k);if("error"===r.status)return d.reject(q,r.value);if(r=r.value)t(q,r);else{q.state=v;q.outcome=k;r=-1;for(var g=q.queue.length;++r<g;)q.queue[r].callFulfilled(k)}return q};d.reject=function(q,k){q.state=h;q.outcome=k;for(var r=-1,g=q.queue.length;++r<g;)q.queue[r].callRejected(k);return q};w.resolve=function(q){return q instanceof
this?q:d.resolve(new this(m),q)};w.reject=function(q){var k=new this(m);return d.reject(k,q)};w.all=function(q){function k(S,M){r.resolve(S).then(function(a){F[M]=a;++H!==g||D||(D=!0,d.resolve(c,F))},function(a){D||(D=!0,d.reject(c,a))})}var r=this;if("[object Array]"!==Object.prototype.toString.call(q))return this.reject(new TypeError("must be an array"));var g=q.length,D=!1;if(!g)return this.resolve([]);for(var F=Array(g),H=0,L=-1,c=new this(m);++L<g;)k(q[L],L);return c};w.race=function(q){function k(L){r.resolve(L).then(function(c){D||
(D=!0,d.resolve(H,c))},function(c){D||(D=!0,d.reject(H,c))})}var r=this;if("[object Array]"!==Object.prototype.toString.call(q))return this.reject(new TypeError("must be an array"));var g=q.length,D=!1;if(!g)return this.resolve([]);for(var F=-1,H=new this(m);++F<g;)k(q[F]);return H}},{immediate:36}],38:[function(p,J,B){B=p("./lib/utils/common").assign;var m=p("./lib/deflate"),w=p("./lib/inflate");p=p("./lib/zlib/constants");var e={};B(e,m,w,p);J.exports=e},{"./lib/deflate":39,"./lib/inflate":40,"./lib/utils/common":41,
"./lib/zlib/constants":44}],39:[function(p,J,B){function m(d){if(!(this instanceof m))return new m(d);d=this.options=n.assign({level:-1,method:8,chunkSize:16384,windowBits:15,memLevel:8,strategy:0,to:""},d||{});d.raw&&0<d.windowBits?d.windowBits=-d.windowBits:d.gzip&&0<d.windowBits&&16>d.windowBits&&(d.windowBits+=16);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new l;this.strm.avail_out=0;var h=e.deflateInit2(this.strm,d.level,d.method,d.windowBits,d.memLevel,d.strategy);if(0!==
h)throw Error(t[h]);d.header&&e.deflateSetHeader(this.strm,d.header);if(d.dictionary){d="string"===typeof d.dictionary?u.string2buf(d.dictionary):"[object ArrayBuffer]"===x.call(d.dictionary)?new Uint8Array(d.dictionary):d.dictionary;h=e.deflateSetDictionary(this.strm,d);if(0!==h)throw Error(t[h]);this._dict_set=!0}}function w(d,h){var v=new m(h);v.push(d,!0);if(v.err)throw v.msg||t[v.err];return v.result}var e=p("./zlib/deflate"),n=p("./utils/common"),u=p("./utils/strings"),t=p("./zlib/messages"),
l=p("./zlib/zstream"),x=Object.prototype.toString;m.prototype.push=function(d,h){var v=this.strm,E=this.options.chunkSize;if(this.ended)return!1;var q=h===~~h?h:!0===h?4:0;"string"===typeof d?v.input=u.string2buf(d):"[object ArrayBuffer]"===x.call(d)?v.input=new Uint8Array(d):v.input=d;v.next_in=0;v.avail_in=v.input.length;do{0===v.avail_out&&(v.output=new n.Buf8(E),v.next_out=0,v.avail_out=E);var k=e.deflate(v,q);if(1!==k&&0!==k)return this.onEnd(k),this.ended=!0,!1;if(0===v.avail_out||0===v.avail_in&&
(4===q||2===q))if("string"===this.options.to)this.onData(u.buf2binstring(n.shrinkBuf(v.output,v.next_out)));else this.onData(n.shrinkBuf(v.output,v.next_out))}while((0<v.avail_in||0===v.avail_out)&&1!==k);if(4===q)return k=e.deflateEnd(this.strm),this.onEnd(k),this.ended=!0,0===k;2===q&&(this.onEnd(0),v.avail_out=0);return!0};m.prototype.onData=function(d){this.chunks.push(d)};m.prototype.onEnd=function(d){0===d&&(this.result="string"===this.options.to?this.chunks.join(""):n.flattenChunks(this.chunks));
this.chunks=[];this.err=d;this.msg=this.strm.msg};B.Deflate=m;B.deflate=w;B.deflateRaw=function(d,h){h=h||{};h.raw=!0;return w(d,h)};B.gzip=function(d,h){h=h||{};h.gzip=!0;return w(d,h)}},{"./utils/common":41,"./utils/strings":42,"./zlib/deflate":46,"./zlib/messages":51,"./zlib/zstream":53}],40:[function(p,J,B){function m(v){if(!(this instanceof m))return new m(v);var E=this.options=n.assign({chunkSize:16384,windowBits:0,to:""},v||{});E.raw&&0<=E.windowBits&&16>E.windowBits&&(E.windowBits=-E.windowBits,
0===E.windowBits&&(E.windowBits=-15));!(0<=E.windowBits&&16>E.windowBits)||v&&v.windowBits||(E.windowBits+=32);15<E.windowBits&&48>E.windowBits&&0===(E.windowBits&15)&&(E.windowBits|=15);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new x;this.strm.avail_out=0;v=e.inflateInit2(this.strm,E.windowBits);if(v!==t.Z_OK)throw Error(l[v]);this.header=new d;e.inflateGetHeader(this.strm,this.header)}function w(v,E){var q=new m(E);q.push(v,!0);if(q.err)throw q.msg||l[q.err];return q.result}
var e=p("./zlib/inflate"),n=p("./utils/common"),u=p("./utils/strings"),t=p("./zlib/constants"),l=p("./zlib/messages"),x=p("./zlib/zstream"),d=p("./zlib/gzheader"),h=Object.prototype.toString;m.prototype.push=function(v,E){var q=this.strm,k=this.options.chunkSize,r=this.options.dictionary,g=!1;if(this.ended)return!1;var D=E===~~E?E:!0===E?t.Z_FINISH:t.Z_NO_FLUSH;"string"===typeof v?q.input=u.binstring2buf(v):"[object ArrayBuffer]"===h.call(v)?q.input=new Uint8Array(v):q.input=v;q.next_in=0;q.avail_in=
q.input.length;do{0===q.avail_out&&(q.output=new n.Buf8(k),q.next_out=0,q.avail_out=k);var F=e.inflate(q,t.Z_NO_FLUSH);F===t.Z_NEED_DICT&&r&&(F="string"===typeof r?u.string2buf(r):"[object ArrayBuffer]"===h.call(r)?new Uint8Array(r):r,F=e.inflateSetDictionary(this.strm,F));F===t.Z_BUF_ERROR&&!0===g&&(F=t.Z_OK,g=!1);if(F!==t.Z_STREAM_END&&F!==t.Z_OK)return this.onEnd(F),this.ended=!0,!1;if(q.next_out&&(0===q.avail_out||F===t.Z_STREAM_END||0===q.avail_in&&(D===t.Z_FINISH||D===t.Z_SYNC_FLUSH)))if("string"===
this.options.to){var H=u.utf8border(q.output,q.next_out);var L=q.next_out-H;var c=u.buf2string(q.output,H);q.next_out=L;q.avail_out=k-L;L&&n.arraySet(q.output,q.output,H,L,0);this.onData(c)}else this.onData(n.shrinkBuf(q.output,q.next_out));0===q.avail_in&&0===q.avail_out&&(g=!0)}while((0<q.avail_in||0===q.avail_out)&&F!==t.Z_STREAM_END);F===t.Z_STREAM_END&&(D=t.Z_FINISH);if(D===t.Z_FINISH)return F=e.inflateEnd(this.strm),this.onEnd(F),this.ended=!0,F===t.Z_OK;D===t.Z_SYNC_FLUSH&&(this.onEnd(t.Z_OK),
q.avail_out=0);return!0};m.prototype.onData=function(v){this.chunks.push(v)};m.prototype.onEnd=function(v){v===t.Z_OK&&(this.result="string"===this.options.to?this.chunks.join(""):n.flattenChunks(this.chunks));this.chunks=[];this.err=v;this.msg=this.strm.msg};B.Inflate=m;B.inflate=w;B.inflateRaw=function(v,E){E=E||{};E.raw=!0;return w(v,E)};B.ungzip=w},{"./utils/common":41,"./utils/strings":42,"./zlib/constants":44,"./zlib/gzheader":47,"./zlib/inflate":49,"./zlib/messages":51,"./zlib/zstream":53}],
41:[function(p,J,B){p="undefined"!==typeof Uint8Array&&"undefined"!==typeof Uint16Array&&"undefined"!==typeof Int32Array;B.assign=function(e){for(var n=Array.prototype.slice.call(arguments,1);n.length;){var u=n.shift();if(u){if("object"!==typeof u)throw new TypeError(u+"must be non-object");for(var t in u)u.hasOwnProperty(t)&&(e[t]=u[t])}}return e};B.shrinkBuf=function(e,n){if(e.length===n)return e;if(e.subarray)return e.subarray(0,n);e.length=n;return e};var m={arraySet:function(e,n,u,t,l){if(n.subarray&&
e.subarray)e.set(n.subarray(u,u+t),l);else for(var x=0;x<t;x++)e[l+x]=n[u+x]},flattenChunks:function(e){var n,u;var t=u=0;for(n=e.length;t<n;t++)u+=e[t].length;var l=new Uint8Array(u);t=u=0;for(n=e.length;t<n;t++){var x=e[t];l.set(x,u);u+=x.length}return l}},w={arraySet:function(e,n,u,t,l){for(var x=0;x<t;x++)e[l+x]=n[u+x]},flattenChunks:function(e){return[].concat.apply([],e)}};B.setTyped=function(e){e?(B.Buf8=Uint8Array,B.Buf16=Uint16Array,B.Buf32=Int32Array,B.assign(B,m)):(B.Buf8=Array,B.Buf16=
Array,B.Buf32=Array,B.assign(B,w))};B.setTyped(p)},{}],42:[function(p,J,B){function m(t,l){if(65537>l&&(t.subarray&&n||!t.subarray&&e))return String.fromCharCode.apply(null,w.shrinkBuf(t,l));for(var x="",d=0;d<l;d++)x+=String.fromCharCode(t[d]);return x}var w=p("./common"),e=!0,n=!0;try{String.fromCharCode.apply(null,[0])}catch(t){e=!1}try{String.fromCharCode.apply(null,new Uint8Array(1))}catch(t){n=!1}var u=new w.Buf8(256);for(p=0;256>p;p++)u[p]=252<=p?6:248<=p?5:240<=p?4:224<=p?3:192<=p?2:1;u[254]=
u[254]=1;B.string2buf=function(t){var l,x,d=t.length,h=0;for(l=0;l<d;l++){var v=t.charCodeAt(l);if(55296===(v&64512)&&l+1<d){var E=t.charCodeAt(l+1);56320===(E&64512)&&(v=65536+(v-55296<<10)+(E-56320),l++)}h+=128>v?1:2048>v?2:65536>v?3:4}var q=new w.Buf8(h);for(l=x=0;x<h;l++)v=t.charCodeAt(l),55296===(v&64512)&&l+1<d&&(E=t.charCodeAt(l+1),56320===(E&64512)&&(v=65536+(v-55296<<10)+(E-56320),l++)),128>v?q[x++]=v:(2048>v?q[x++]=192|v>>>6:(65536>v?q[x++]=224|v>>>12:(q[x++]=240|v>>>18,q[x++]=128|v>>>12&
63),q[x++]=128|v>>>6&63),q[x++]=128|v&63);return q};B.buf2binstring=function(t){return m(t,t.length)};B.binstring2buf=function(t){for(var l=new w.Buf8(t.length),x=0,d=l.length;x<d;x++)l[x]=t.charCodeAt(x);return l};B.buf2string=function(t,l){var x,d,h=l||t.length,v=Array(2*h);for(x=d=0;x<h;){var E=t[x++];if(128>E)v[d++]=E;else{var q=u[E];if(4<q)v[d++]=65533,x+=q-1;else{for(E&=2===q?31:3===q?15:7;1<q&&x<h;)E=E<<6|t[x++]&63,q--;1<q?v[d++]=65533:65536>E?v[d++]=E:(E-=65536,v[d++]=55296|E>>10&1023,v[d++]=
56320|E&1023)}}}return m(v,d)};B.utf8border=function(t,l){var x;l=l||t.length;l>t.length&&(l=t.length);for(x=l-1;0<=x&&128===(t[x]&192);)x--;return 0>x||0===x?l:x+u[t[x]]>l?x:l}},{"./common":41}],43:[function(p,J,B){J.exports=function(m,w,e,n){var u=m&65535|0;m=m>>>16&65535|0;for(var t;0!==e;){t=2E3<e?2E3:e;e-=t;do u=u+w[n++]|0,m=m+u|0;while(--t);u%=65521;m%=65521}return u|m<<16|0}},{}],44:[function(p,J,B){J.exports={Z_NO_FLUSH:0,Z_PARTIAL_FLUSH:1,Z_SYNC_FLUSH:2,Z_FULL_FLUSH:3,Z_FINISH:4,Z_BLOCK:5,
Z_TREES:6,Z_OK:0,Z_STREAM_END:1,Z_NEED_DICT:2,Z_ERRNO:-1,Z_STREAM_ERROR:-2,Z_DATA_ERROR:-3,Z_BUF_ERROR:-5,Z_NO_COMPRESSION:0,Z_BEST_SPEED:1,Z_BEST_COMPRESSION:9,Z_DEFAULT_COMPRESSION:-1,Z_FILTERED:1,Z_HUFFMAN_ONLY:2,Z_RLE:3,Z_FIXED:4,Z_DEFAULT_STRATEGY:0,Z_BINARY:0,Z_TEXT:1,Z_UNKNOWN:2,Z_DEFLATED:8}},{}],45:[function(p,J,B){var m=function(){for(var w,e=[],n=0;256>n;n++){w=n;for(var u=0;8>u;u++)w=w&1?3988292384^w>>>1:w>>>1;e[n]=w}return e}();J.exports=function(w,e,n,u){n=u+n;for(w^=-1;u<n;u++)w=w>>>
8^m[(w^e[u])&255];return w^-1}},{}],46:[function(p,J,B){function m(a,A){a.msg=S[A];return A}function w(a){for(var A=a.length;0<=--A;)a[A]=0}function e(a){var A=a.state,f=A.pending;f>a.avail_out&&(f=a.avail_out);0!==f&&(F.arraySet(a.output,A.pending_buf,A.pending_out,f,a.next_out),a.next_out+=f,A.pending_out+=f,a.total_out+=f,a.avail_out-=f,A.pending-=f,0===A.pending&&(A.pending_out=0))}function n(a,A){H._tr_flush_block(a,0<=a.block_start?a.block_start:-1,a.strstart-a.block_start,A);a.block_start=
a.strstart;e(a.strm)}function u(a,A){a.pending_buf[a.pending++]=A}function t(a,A){a.pending_buf[a.pending++]=A>>>8&255;a.pending_buf[a.pending++]=A&255}function l(a,A){var f=a.max_chain_length,z=a.strstart,y=a.prev_length,C=a.nice_match,T=a.strstart>a.w_size-262?a.strstart-(a.w_size-262):0,K=a.window,X=a.w_mask,O=a.prev,b=a.strstart+258,G=K[z+y-1],I=K[z+y];a.prev_length>=a.good_match&&(f>>=2);C>a.lookahead&&(C=a.lookahead);do{var N=A;if(K[N+y]===I&&K[N+y-1]===G&&K[N]===K[z]&&K[++N]===K[z+1]){z+=2;
for(N++;K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&K[++z]===K[++N]&&z<b;);N=258-(b-z);z=b-258;if(N>y){a.match_start=A;y=N;if(N>=C)break;G=K[z+y-1];I=K[z+y]}}}while((A=O[A&X])>T&&0!==--f);return y<=a.lookahead?y:a.lookahead}function x(a){var A=a.w_size,f;do{var z=a.window_size-a.lookahead-a.strstart;if(a.strstart>=A+(A-262)){F.arraySet(a.window,a.window,A,A,0);a.match_start-=A;a.strstart-=A;a.block_start-=A;var y=f=a.hash_size;
do{var C=a.head[--y];a.head[y]=C>=A?C-A:0}while(--f);y=f=A;do C=a.prev[--y],a.prev[y]=C>=A?C-A:0;while(--f);z+=A}if(0===a.strm.avail_in)break;y=a.strm;f=a.window;C=a.strstart+a.lookahead;var T=y.avail_in;T>z&&(T=z);0===T?f=0:(y.avail_in-=T,F.arraySet(f,y.input,y.next_in,T,C),1===y.state.wrap?y.adler=L(y.adler,f,T,C):2===y.state.wrap&&(y.adler=c(y.adler,f,T,C)),y.next_in+=T,y.total_in+=T,f=T);a.lookahead+=f;if(3<=a.lookahead+a.insert)for(z=a.strstart-a.insert,a.ins_h=a.window[z],a.ins_h=(a.ins_h<<
a.hash_shift^a.window[z+1])&a.hash_mask;a.insert&&!(a.ins_h=(a.ins_h<<a.hash_shift^a.window[z+3-1])&a.hash_mask,a.prev[z&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=z,z++,a.insert--,3>a.lookahead+a.insert););}while(262>a.lookahead&&0!==a.strm.avail_in)}function d(a,A){for(var f;;){if(262>a.lookahead){x(a);if(262>a.lookahead&&0===A)return 1;if(0===a.lookahead)break}f=0;3<=a.lookahead&&(a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,f=a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],
a.head[a.ins_h]=a.strstart);0!==f&&a.strstart-f<=a.w_size-262&&(a.match_length=l(a,f));if(3<=a.match_length)if(f=H._tr_tally(a,a.strstart-a.match_start,a.match_length-3),a.lookahead-=a.match_length,a.match_length<=a.max_lazy_match&&3<=a.lookahead){a.match_length--;do a.strstart++,a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart;while(0!==--a.match_length);a.strstart++}else a.strstart+=a.match_length,a.match_length=
0,a.ins_h=a.window[a.strstart],a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+1])&a.hash_mask;else f=H._tr_tally(a,0,a.window[a.strstart]),a.lookahead--,a.strstart++;if(f&&(n(a,!1),0===a.strm.avail_out))return 1}a.insert=2>a.strstart?a.strstart:2;return 4===A?(n(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(n(a,!1),0===a.strm.avail_out)?1:2}function h(a,A){for(var f,z;;){if(262>a.lookahead){x(a);if(262>a.lookahead&&0===A)return 1;if(0===a.lookahead)break}f=0;3<=a.lookahead&&(a.ins_h=(a.ins_h<<
a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,f=a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart);a.prev_length=a.match_length;a.prev_match=a.match_start;a.match_length=2;0!==f&&a.prev_length<a.max_lazy_match&&a.strstart-f<=a.w_size-262&&(a.match_length=l(a,f),5>=a.match_length&&(1===a.strategy||3===a.match_length&&4096<a.strstart-a.match_start)&&(a.match_length=2));if(3<=a.prev_length&&a.match_length<=a.prev_length){z=a.strstart+a.lookahead-3;f=H._tr_tally(a,a.strstart-
1-a.prev_match,a.prev_length-3);a.lookahead-=a.prev_length-1;a.prev_length-=2;do++a.strstart<=z&&(a.ins_h=(a.ins_h<<a.hash_shift^a.window[a.strstart+3-1])&a.hash_mask,a.prev[a.strstart&a.w_mask]=a.head[a.ins_h],a.head[a.ins_h]=a.strstart);while(0!==--a.prev_length);a.match_available=0;a.match_length=2;a.strstart++;if(f&&(n(a,!1),0===a.strm.avail_out))return 1}else if(a.match_available){if((f=H._tr_tally(a,0,a.window[a.strstart-1]))&&n(a,!1),a.strstart++,a.lookahead--,0===a.strm.avail_out)return 1}else a.match_available=
1,a.strstart++,a.lookahead--}a.match_available&&(H._tr_tally(a,0,a.window[a.strstart-1]),a.match_available=0);a.insert=2>a.strstart?a.strstart:2;return 4===A?(n(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(n(a,!1),0===a.strm.avail_out)?1:2}function v(a,A){for(var f,z,y,C=a.window;;){if(258>=a.lookahead){x(a);if(258>=a.lookahead&&0===A)return 1;if(0===a.lookahead)break}a.match_length=0;if(3<=a.lookahead&&0<a.strstart&&(z=a.strstart-1,f=C[z],f===C[++z]&&f===C[++z]&&f===C[++z])){for(y=a.strstart+258;f===
C[++z]&&f===C[++z]&&f===C[++z]&&f===C[++z]&&f===C[++z]&&f===C[++z]&&f===C[++z]&&f===C[++z]&&z<y;);a.match_length=258-(y-z);a.match_length>a.lookahead&&(a.match_length=a.lookahead)}3<=a.match_length?(f=H._tr_tally(a,1,a.match_length-3),a.lookahead-=a.match_length,a.strstart+=a.match_length,a.match_length=0):(f=H._tr_tally(a,0,a.window[a.strstart]),a.lookahead--,a.strstart++);if(f&&(n(a,!1),0===a.strm.avail_out))return 1}a.insert=0;return 4===A?(n(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(n(a,!1),
0===a.strm.avail_out)?1:2}function E(a,A){for(var f;;){if(0===a.lookahead&&(x(a),0===a.lookahead)){if(0===A)return 1;break}a.match_length=0;f=H._tr_tally(a,0,a.window[a.strstart]);a.lookahead--;a.strstart++;if(f&&(n(a,!1),0===a.strm.avail_out))return 1}a.insert=0;return 4===A?(n(a,!0),0===a.strm.avail_out?3:4):a.last_lit&&(n(a,!1),0===a.strm.avail_out)?1:2}function q(a,A,f,z,y){this.good_length=a;this.max_lazy=A;this.nice_length=f;this.max_chain=z;this.func=y}function k(){this.strm=null;this.status=
0;this.pending_buf=null;this.wrap=this.pending=this.pending_out=this.pending_buf_size=0;this.gzhead=null;this.gzindex=0;this.method=8;this.last_flush=-1;this.w_mask=this.w_bits=this.w_size=0;this.window=null;this.window_size=0;this.head=this.prev=null;this.nice_match=this.good_match=this.strategy=this.level=this.max_lazy_match=this.max_chain_length=this.prev_length=this.lookahead=this.match_start=this.strstart=this.match_available=this.prev_match=this.match_length=this.block_start=this.hash_shift=
this.hash_mask=this.hash_bits=this.hash_size=this.ins_h=0;this.dyn_ltree=new F.Buf16(1146);this.dyn_dtree=new F.Buf16(122);this.bl_tree=new F.Buf16(78);w(this.dyn_ltree);w(this.dyn_dtree);w(this.bl_tree);this.bl_desc=this.d_desc=this.l_desc=null;this.bl_count=new F.Buf16(16);this.heap=new F.Buf16(573);w(this.heap);this.heap_max=this.heap_len=0;this.depth=new F.Buf16(573);w(this.depth);this.bi_valid=this.bi_buf=this.insert=this.matches=this.static_len=this.opt_len=this.d_buf=this.last_lit=this.lit_bufsize=
this.l_buf=0}function r(a){if(!a||!a.state)return m(a,-2);a.total_in=a.total_out=0;a.data_type=2;var A=a.state;A.pending=0;A.pending_out=0;0>A.wrap&&(A.wrap=-A.wrap);A.status=A.wrap?42:113;a.adler=2===A.wrap?0:1;A.last_flush=0;H._tr_init(A);return 0}function g(a){var A=r(a);0===A&&(a=a.state,a.window_size=2*a.w_size,w(a.head),a.max_lazy_match=M[a.level].max_lazy,a.good_match=M[a.level].good_length,a.nice_match=M[a.level].nice_length,a.max_chain_length=M[a.level].max_chain,a.strstart=0,a.block_start=
0,a.lookahead=0,a.insert=0,a.match_length=a.prev_length=2,a.match_available=0,a.ins_h=0);return A}function D(a,A,f,z,y,C){if(!a)return-2;var T=1;-1===A&&(A=6);0>z?(T=0,z=-z):15<z&&(T=2,z-=16);if(1>y||9<y||8!==f||8>z||15<z||0>A||9<A||0>C||4<C)return m(a,-2);8===z&&(z=9);var K=new k;a.state=K;K.strm=a;K.wrap=T;K.gzhead=null;K.w_bits=z;K.w_size=1<<K.w_bits;K.w_mask=K.w_size-1;K.hash_bits=y+7;K.hash_size=1<<K.hash_bits;K.hash_mask=K.hash_size-1;K.hash_shift=~~((K.hash_bits+3-1)/3);K.window=new F.Buf8(2*
K.w_size);K.head=new F.Buf16(K.hash_size);K.prev=new F.Buf16(K.w_size);K.lit_bufsize=1<<y+6;K.pending_buf_size=4*K.lit_bufsize;K.pending_buf=new F.Buf8(K.pending_buf_size);K.d_buf=1*K.lit_bufsize;K.l_buf=3*K.lit_bufsize;K.level=A;K.strategy=C;K.method=f;return g(a)}var F=p("../utils/common"),H=p("./trees"),L=p("./adler32"),c=p("./crc32"),S=p("./messages");var M=[new q(0,0,0,0,function(a,A){var f=65535;for(f>a.pending_buf_size-5&&(f=a.pending_buf_size-5);;){if(1>=a.lookahead){x(a);if(0===a.lookahead&&
0===A)return 1;if(0===a.lookahead)break}a.strstart+=a.lookahead;a.lookahead=0;var z=a.block_start+f;if(0===a.strstart||a.strstart>=z)if(a.lookahead=a.strstart-z,a.strstart=z,n(a,!1),0===a.strm.avail_out)return 1;if(a.strstart-a.block_start>=a.w_size-262&&(n(a,!1),0===a.strm.avail_out))return 1}a.insert=0;if(4===A)return n(a,!0),0===a.strm.avail_out?3:4;a.strstart>a.block_start&&n(a,!1);return 1}),new q(4,4,8,4,d),new q(4,5,16,8,d),new q(4,6,32,32,d),new q(4,4,16,16,h),new q(8,16,32,32,h),new q(8,
16,128,128,h),new q(8,32,128,256,h),new q(32,128,258,1024,h),new q(32,258,258,4096,h)];B.deflateInit=function(a,A){return D(a,A,8,15,8,0)};B.deflateInit2=D;B.deflateReset=g;B.deflateResetKeep=r;B.deflateSetHeader=function(a,A){if(!a||!a.state||2!==a.state.wrap)return-2;a.state.gzhead=A;return 0};B.deflate=function(a,A){if(!a||!a.state||5<A||0>A)return a?m(a,-2):-2;var f=a.state;if(!a.output||!a.input&&0!==a.avail_in||666===f.status&&4!==A)return m(a,0===a.avail_out?-5:-2);f.strm=a;var z=f.last_flush;
f.last_flush=A;if(42===f.status)if(2===f.wrap)a.adler=0,u(f,31),u(f,139),u(f,8),f.gzhead?(u(f,(f.gzhead.text?1:0)+(f.gzhead.hcrc?2:0)+(f.gzhead.extra?4:0)+(f.gzhead.name?8:0)+(f.gzhead.comment?16:0)),u(f,f.gzhead.time&255),u(f,f.gzhead.time>>8&255),u(f,f.gzhead.time>>16&255),u(f,f.gzhead.time>>24&255),u(f,9===f.level?2:2<=f.strategy||2>f.level?4:0),u(f,f.gzhead.os&255),f.gzhead.extra&&f.gzhead.extra.length&&(u(f,f.gzhead.extra.length&255),u(f,f.gzhead.extra.length>>8&255)),f.gzhead.hcrc&&(a.adler=
c(a.adler,f.pending_buf,f.pending,0)),f.gzindex=0,f.status=69):(u(f,0),u(f,0),u(f,0),u(f,0),u(f,0),u(f,9===f.level?2:2<=f.strategy||2>f.level?4:0),u(f,3),f.status=113);else{var y=8+(f.w_bits-8<<4)<<8;y|=(2<=f.strategy||2>f.level?0:6>f.level?1:6===f.level?2:3)<<6;0!==f.strstart&&(y|=32);f.status=113;t(f,y+(31-y%31));0!==f.strstart&&(t(f,a.adler>>>16),t(f,a.adler&65535));a.adler=1}if(69===f.status)if(f.gzhead.extra){for(y=f.pending;f.gzindex<(f.gzhead.extra.length&65535)&&(f.pending!==f.pending_buf_size||
(f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y)),e(a),y=f.pending,f.pending!==f.pending_buf_size));)u(f,f.gzhead.extra[f.gzindex]&255),f.gzindex++;f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y));f.gzindex===f.gzhead.extra.length&&(f.gzindex=0,f.status=73)}else f.status=73;if(73===f.status)if(f.gzhead.name){y=f.pending;do{if(f.pending===f.pending_buf_size&&(f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y)),e(a),y=
f.pending,f.pending===f.pending_buf_size)){var C=1;break}C=f.gzindex<f.gzhead.name.length?f.gzhead.name.charCodeAt(f.gzindex++)&255:0;u(f,C)}while(0!==C);f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y));0===C&&(f.gzindex=0,f.status=91)}else f.status=91;if(91===f.status)if(f.gzhead.comment){y=f.pending;do{if(f.pending===f.pending_buf_size&&(f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y)),e(a),y=f.pending,f.pending===f.pending_buf_size)){C=1;
break}C=f.gzindex<f.gzhead.comment.length?f.gzhead.comment.charCodeAt(f.gzindex++)&255:0;u(f,C)}while(0!==C);f.gzhead.hcrc&&f.pending>y&&(a.adler=c(a.adler,f.pending_buf,f.pending-y,y));0===C&&(f.status=103)}else f.status=103;103===f.status&&(f.gzhead.hcrc?(f.pending+2>f.pending_buf_size&&e(a),f.pending+2<=f.pending_buf_size&&(u(f,a.adler&255),u(f,a.adler>>8&255),a.adler=0,f.status=113)):f.status=113);if(0!==f.pending){if(e(a),0===a.avail_out)return f.last_flush=-1,0}else if(0===a.avail_in&&(A<<1)-
(4<A?9:0)<=(z<<1)-(4<z?9:0)&&4!==A)return m(a,-5);if(666===f.status&&0!==a.avail_in)return m(a,-5);if(0!==a.avail_in||0!==f.lookahead||0!==A&&666!==f.status){z=2===f.strategy?E(f,A):3===f.strategy?v(f,A):M[f.level].func(f,A);if(3===z||4===z)f.status=666;if(1===z||3===z)return 0===a.avail_out&&(f.last_flush=-1),0;if(2===z&&(1===A?H._tr_align(f):5!==A&&(H._tr_stored_block(f,0,0,!1),3===A&&(w(f.head),0===f.lookahead&&(f.strstart=0,f.block_start=0,f.insert=0))),e(a),0===a.avail_out))return f.last_flush=
-1,0}if(4!==A)return 0;if(0>=f.wrap)return 1;2===f.wrap?(u(f,a.adler&255),u(f,a.adler>>8&255),u(f,a.adler>>16&255),u(f,a.adler>>24&255),u(f,a.total_in&255),u(f,a.total_in>>8&255),u(f,a.total_in>>16&255),u(f,a.total_in>>24&255)):(t(f,a.adler>>>16),t(f,a.adler&65535));e(a);0<f.wrap&&(f.wrap=-f.wrap);return 0!==f.pending?0:1};B.deflateEnd=function(a){if(!a||!a.state)return-2;var A=a.state.status;if(42!==A&&69!==A&&73!==A&&91!==A&&103!==A&&113!==A&&666!==A)return m(a,-2);a.state=null;return 113===A?m(a,
-3):0};B.deflateSetDictionary=function(a,A){var f=A.length;if(!a||!a.state)return-2;var z=a.state;var y=z.wrap;if(2===y||1===y&&42!==z.status||z.lookahead)return-2;1===y&&(a.adler=L(a.adler,A,f,0));z.wrap=0;if(f>=z.w_size){0===y&&(w(z.head),z.strstart=0,z.block_start=0,z.insert=0);var C=new F.Buf8(z.w_size);F.arraySet(C,A,f-z.w_size,z.w_size,0);A=C;f=z.w_size}C=a.avail_in;var T=a.next_in;var K=a.input;a.avail_in=f;a.next_in=0;a.input=A;for(x(z);3<=z.lookahead;){f=z.strstart;var X=z.lookahead-2;do z.ins_h=
(z.ins_h<<z.hash_shift^z.window[f+3-1])&z.hash_mask,z.prev[f&z.w_mask]=z.head[z.ins_h],z.head[z.ins_h]=f,f++;while(--X);z.strstart=f;z.lookahead=2;x(z)}z.strstart+=z.lookahead;z.block_start=z.strstart;z.insert=z.lookahead;z.lookahead=0;z.match_length=z.prev_length=2;z.match_available=0;a.next_in=T;a.input=K;a.avail_in=C;z.wrap=y;return 0};B.deflateInfo="pako deflate (from Nodeca project)"},{"../utils/common":41,"./adler32":43,"./crc32":45,"./messages":51,"./trees":52}],47:[function(p,J,B){J.exports=
function(){this.os=this.xflags=this.time=this.text=0;this.extra=null;this.extra_len=0;this.comment=this.name="";this.hcrc=0;this.done=!1}},{}],48:[function(p,J,B){J.exports=function(m,w){var e=m.state;var n=m.next_in;var u=m.input;var t=n+(m.avail_in-5);var l=m.next_out;var x=m.output;var d=l-(w-m.avail_out);var h=l+(m.avail_out-257);var v=e.dmax;var E=e.wsize;var q=e.whave;var k=e.wnext;var r=e.window;var g=e.hold;var D=e.bits;var F=e.lencode;var H=e.distcode;var L=(1<<e.lenbits)-1;var c=(1<<e.distbits)-
1;a:do{15>D&&(g+=u[n++]<<D,D+=8,g+=u[n++]<<D,D+=8);var S=F[g&L];b:for(;;){var M=S>>>24;g>>>=M;D-=M;M=S>>>16&255;if(0===M)x[l++]=S&65535;else if(M&16){var a=S&65535;if(M&=15)D<M&&(g+=u[n++]<<D,D+=8),a+=g&(1<<M)-1,g>>>=M,D-=M;15>D&&(g+=u[n++]<<D,D+=8,g+=u[n++]<<D,D+=8);S=H[g&c];c:for(;;){M=S>>>24;g>>>=M;D-=M;M=S>>>16&255;if(M&16){S&=65535;M&=15;D<M&&(g+=u[n++]<<D,D+=8,D<M&&(g+=u[n++]<<D,D+=8));S+=g&(1<<M)-1;if(S>v){m.msg="invalid distance too far back";e.mode=30;break a}g>>>=M;D-=M;M=l-d;if(S>M){M=
S-M;if(M>q&&e.sane){m.msg="invalid distance too far back";e.mode=30;break a}var A=0;var f=r;if(0===k){if(A+=E-M,M<a){a-=M;do x[l++]=r[A++];while(--M);A=l-S;f=x}}else if(k<M){if(A+=E+k-M,M-=k,M<a){a-=M;do x[l++]=r[A++];while(--M);A=0;if(k<a){M=k;a-=M;do x[l++]=r[A++];while(--M);A=l-S;f=x}}}else if(A+=k-M,M<a){a-=M;do x[l++]=r[A++];while(--M);A=l-S;f=x}for(;2<a;)x[l++]=f[A++],x[l++]=f[A++],x[l++]=f[A++],a-=3;a&&(x[l++]=f[A++],1<a&&(x[l++]=f[A++]))}else{A=l-S;do x[l++]=x[A++],x[l++]=x[A++],x[l++]=x[A++],
a-=3;while(2<a);a&&(x[l++]=x[A++],1<a&&(x[l++]=x[A++]))}}else if(0===(M&64)){S=H[(S&65535)+(g&(1<<M)-1)];continue c}else{m.msg="invalid distance code";e.mode=30;break a}break}}else if(0===(M&64)){S=F[(S&65535)+(g&(1<<M)-1)];continue b}else{M&32?e.mode=12:(m.msg="invalid literal/length code",e.mode=30);break a}break}}while(n<t&&l<h);a=D>>3;n-=a;D-=a<<3;m.next_in=n;m.next_out=l;m.avail_in=n<t?5+(t-n):5-(n-t);m.avail_out=l<h?257+(h-l):257-(l-h);e.hold=g&(1<<D)-1;e.bits=D}},{}],49:[function(p,J,B){function m(g){return(g>>>
24&255)+(g>>>8&65280)+((g&65280)<<8)+((g&255)<<24)}function w(){this.mode=0;this.last=!1;this.wrap=0;this.havedict=!1;this.total=this.check=this.dmax=this.flags=0;this.head=null;this.wnext=this.whave=this.wsize=this.wbits=0;this.window=null;this.extra=this.offset=this.length=this.bits=this.hold=0;this.distcode=this.lencode=null;this.have=this.ndist=this.nlen=this.ncode=this.distbits=this.lenbits=0;this.next=null;this.lens=new x.Buf16(320);this.work=new x.Buf16(288);this.distdyn=this.lendyn=null;this.was=
this.back=this.sane=0}function e(g){if(!g||!g.state)return-2;var D=g.state;g.total_in=g.total_out=D.total=0;g.msg="";D.wrap&&(g.adler=D.wrap&1);D.mode=1;D.last=0;D.havedict=0;D.dmax=32768;D.head=null;D.hold=0;D.bits=0;D.lencode=D.lendyn=new x.Buf32(852);D.distcode=D.distdyn=new x.Buf32(592);D.sane=1;D.back=-1;return 0}function n(g){if(!g||!g.state)return-2;var D=g.state;D.wsize=0;D.whave=0;D.wnext=0;return e(g)}function u(g,D){if(!g||!g.state)return-2;var F=g.state;if(0>D){var H=0;D=-D}else H=(D>>
4)+1,48>D&&(D&=15);if(D&&(8>D||15<D))return-2;null!==F.window&&F.wbits!==D&&(F.window=null);F.wrap=H;F.wbits=D;return n(g)}function t(g,D){if(!g)return-2;var F=new w;g.state=F;F.window=null;F=u(g,D);0!==F&&(g.state=null);return F}function l(g,D,F,H){var L=g.state;null===L.window&&(L.wsize=1<<L.wbits,L.wnext=0,L.whave=0,L.window=new x.Buf8(L.wsize));H>=L.wsize?(x.arraySet(L.window,D,F-L.wsize,L.wsize,0),L.wnext=0,L.whave=L.wsize):(g=L.wsize-L.wnext,g>H&&(g=H),x.arraySet(L.window,D,F-H,g,L.wnext),(H-=
g)?(x.arraySet(L.window,D,F-H,H,0),L.wnext=H,L.whave=L.wsize):(L.wnext+=g,L.wnext===L.wsize&&(L.wnext=0),L.whave<L.wsize&&(L.whave+=g)));return 0}var x=p("../utils/common"),d=p("./adler32"),h=p("./crc32"),v=p("./inffast"),E=p("./inftrees"),q=!0,k,r;B.inflateReset=n;B.inflateReset2=u;B.inflateResetKeep=e;B.inflateInit=function(g){return t(g,15)};B.inflateInit2=t;B.inflate=function(g,D){var F,H=new x.Buf8(4),L=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];if(!g||!g.state||!g.output||!g.input&&0!==
g.avail_in)return-2;var c=g.state;12===c.mode&&(c.mode=13);var S=g.next_out;var M=g.output;var a=g.avail_out;var A=g.next_in;var f=g.input;var z=g.avail_in;var y=c.hold;var C=c.bits;var T=z;var K=a;var X=0;a:for(;;)switch(c.mode){case 1:if(0===c.wrap){c.mode=13;break}for(;16>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if(c.wrap&2&&35615===y){c.check=0;H[0]=y&255;H[1]=y>>>8&255;c.check=h(c.check,H,2,0);C=y=0;c.mode=2;break}c.flags=0;c.head&&(c.head.done=!1);if(!(c.wrap&1)||(((y&255)<<8)+(y>>8))%31){g.msg=
"incorrect header check";c.mode=30;break}if(8!==(y&15)){g.msg="unknown compression method";c.mode=30;break}y>>>=4;C-=4;var O=(y&15)+8;if(0===c.wbits)c.wbits=O;else if(O>c.wbits){g.msg="invalid window size";c.mode=30;break}c.dmax=1<<O;g.adler=c.check=1;c.mode=y&512?10:12;C=y=0;break;case 2:for(;16>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.flags=y;if(8!==(c.flags&255)){g.msg="unknown compression method";c.mode=30;break}if(c.flags&57344){g.msg="unknown header flags set";c.mode=30;break}c.head&&(c.head.text=
y>>8&1);c.flags&512&&(H[0]=y&255,H[1]=y>>>8&255,c.check=h(c.check,H,2,0));C=y=0;c.mode=3;case 3:for(;32>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.head&&(c.head.time=y);c.flags&512&&(H[0]=y&255,H[1]=y>>>8&255,H[2]=y>>>16&255,H[3]=y>>>24&255,c.check=h(c.check,H,4,0));C=y=0;c.mode=4;case 4:for(;16>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.head&&(c.head.xflags=y&255,c.head.os=y>>8);c.flags&512&&(H[0]=y&255,H[1]=y>>>8&255,c.check=h(c.check,H,2,0));C=y=0;c.mode=5;case 5:if(c.flags&1024){for(;16>C;){if(0===
z)break a;z--;y+=f[A++]<<C;C+=8}c.length=y;c.head&&(c.head.extra_len=y);c.flags&512&&(H[0]=y&255,H[1]=y>>>8&255,c.check=h(c.check,H,2,0));C=y=0}else c.head&&(c.head.extra=null);c.mode=6;case 6:if(c.flags&1024){var b=c.length;b>z&&(b=z);b&&(c.head&&(O=c.head.extra_len-c.length,c.head.extra||(c.head.extra=Array(c.head.extra_len)),x.arraySet(c.head.extra,f,A,b,O)),c.flags&512&&(c.check=h(c.check,f,b,A)),z-=b,A+=b,c.length-=b);if(c.length)break a}c.length=0;c.mode=7;case 7:if(c.flags&2048){if(0===z)break a;
b=0;do O=f[A+b++],c.head&&O&&65536>c.length&&(c.head.name+=String.fromCharCode(O));while(O&&b<z);c.flags&512&&(c.check=h(c.check,f,b,A));z-=b;A+=b;if(O)break a}else c.head&&(c.head.name=null);c.length=0;c.mode=8;case 8:if(c.flags&4096){if(0===z)break a;b=0;do O=f[A+b++],c.head&&O&&65536>c.length&&(c.head.comment+=String.fromCharCode(O));while(O&&b<z);c.flags&512&&(c.check=h(c.check,f,b,A));z-=b;A+=b;if(O)break a}else c.head&&(c.head.comment=null);c.mode=9;case 9:if(c.flags&512){for(;16>C;){if(0===
z)break a;z--;y+=f[A++]<<C;C+=8}if(y!==(c.check&65535)){g.msg="header crc mismatch";c.mode=30;break}C=y=0}c.head&&(c.head.hcrc=c.flags>>9&1,c.head.done=!0);g.adler=c.check=0;c.mode=12;break;case 10:for(;32>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}g.adler=c.check=m(y);C=y=0;c.mode=11;case 11:if(0===c.havedict)return g.next_out=S,g.avail_out=a,g.next_in=A,g.avail_in=z,c.hold=y,c.bits=C,2;g.adler=c.check=1;c.mode=12;case 12:if(5===D||6===D)break a;case 13:if(c.last){y>>>=C&7;C-=C&7;c.mode=27;break}for(;3>
C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.last=y&1;y>>>=1;--C;switch(y&3){case 0:c.mode=14;break;case 1:O=c;if(q){k=new x.Buf32(512);r=new x.Buf32(32);for(b=0;144>b;)O.lens[b++]=8;for(;256>b;)O.lens[b++]=9;for(;280>b;)O.lens[b++]=7;for(;288>b;)O.lens[b++]=8;E(1,O.lens,0,288,k,0,O.work,{bits:9});for(b=0;32>b;)O.lens[b++]=5;E(2,O.lens,0,32,r,0,O.work,{bits:5});q=!1}O.lencode=k;O.lenbits=9;O.distcode=r;O.distbits=5;c.mode=20;if(6===D){y>>>=2;C-=2;break a}break;case 2:c.mode=17;break;case 3:g.msg=
"invalid block type",c.mode=30}y>>>=2;C-=2;break;case 14:y>>>=C&7;for(C-=C&7;32>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if((y&65535)!==(y>>>16^65535)){g.msg="invalid stored block lengths";c.mode=30;break}c.length=y&65535;C=y=0;c.mode=15;if(6===D)break a;case 15:c.mode=16;case 16:if(b=c.length){b>z&&(b=z);b>a&&(b=a);if(0===b)break a;x.arraySet(M,f,A,b,S);z-=b;A+=b;a-=b;S+=b;c.length-=b;break}c.mode=12;break;case 17:for(;14>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.nlen=(y&31)+257;y>>>=5;C-=5;
c.ndist=(y&31)+1;y>>>=5;C-=5;c.ncode=(y&15)+4;y>>>=4;C-=4;if(286<c.nlen||30<c.ndist){g.msg="too many length or distance symbols";c.mode=30;break}c.have=0;c.mode=18;case 18:for(;c.have<c.ncode;){for(;3>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.lens[L[c.have++]]=y&7;y>>>=3;C-=3}for(;19>c.have;)c.lens[L[c.have++]]=0;c.lencode=c.lendyn;c.lenbits=7;b={bits:c.lenbits};X=E(0,c.lens,0,19,c.lencode,0,c.work,b);c.lenbits=b.bits;if(X){g.msg="invalid code lengths set";c.mode=30;break}c.have=0;c.mode=19;case 19:for(;c.have<
c.nlen+c.ndist;){for(;;){var G=c.lencode[y&(1<<c.lenbits)-1];b=G>>>24;G&=65535;if(b<=C)break;if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if(16>G)y>>>=b,C-=b,c.lens[c.have++]=G;else{if(16===G){for(O=b+2;C<O;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}y>>>=b;C-=b;if(0===c.have){g.msg="invalid bit length repeat";c.mode=30;break}O=c.lens[c.have-1];b=3+(y&3);y>>>=2;C-=2}else if(17===G){for(O=b+3;C<O;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}y>>>=b;C-=b;O=0;b=3+(y&7);y>>>=3;C-=3}else{for(O=b+7;C<O;){if(0===z)break a;
z--;y+=f[A++]<<C;C+=8}y>>>=b;C-=b;O=0;b=11+(y&127);y>>>=7;C-=7}if(c.have+b>c.nlen+c.ndist){g.msg="invalid bit length repeat";c.mode=30;break}for(;b--;)c.lens[c.have++]=O}}if(30===c.mode)break;if(0===c.lens[256]){g.msg="invalid code -- missing end-of-block";c.mode=30;break}c.lenbits=9;b={bits:c.lenbits};X=E(1,c.lens,0,c.nlen,c.lencode,0,c.work,b);c.lenbits=b.bits;if(X){g.msg="invalid literal/lengths set";c.mode=30;break}c.distbits=6;c.distcode=c.distdyn;b={bits:c.distbits};X=E(2,c.lens,c.nlen,c.ndist,
c.distcode,0,c.work,b);c.distbits=b.bits;if(X){g.msg="invalid distances set";c.mode=30;break}c.mode=20;if(6===D)break a;case 20:c.mode=21;case 21:if(6<=z&&258<=a){g.next_out=S;g.avail_out=a;g.next_in=A;g.avail_in=z;c.hold=y;c.bits=C;v(g,K);S=g.next_out;M=g.output;a=g.avail_out;A=g.next_in;f=g.input;z=g.avail_in;y=c.hold;C=c.bits;12===c.mode&&(c.back=-1);break}for(c.back=0;;){G=c.lencode[y&(1<<c.lenbits)-1];b=G>>>24;O=G>>>16&255;G&=65535;if(b<=C)break;if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if(O&&0===
(O&240)){var I=b;var N=O;for(F=G;;){G=c.lencode[F+((y&(1<<I+N)-1)>>I)];b=G>>>24;O=G>>>16&255;G&=65535;if(I+b<=C)break;if(0===z)break a;z--;y+=f[A++]<<C;C+=8}y>>>=I;C-=I;c.back+=I}y>>>=b;C-=b;c.back+=b;c.length=G;if(0===O){c.mode=26;break}if(O&32){c.back=-1;c.mode=12;break}if(O&64){g.msg="invalid literal/length code";c.mode=30;break}c.extra=O&15;c.mode=22;case 22:if(c.extra){for(O=c.extra;C<O;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}c.length+=y&(1<<c.extra)-1;y>>>=c.extra;C-=c.extra;c.back+=c.extra}c.was=
c.length;c.mode=23;case 23:for(;;){G=c.distcode[y&(1<<c.distbits)-1];b=G>>>24;O=G>>>16&255;G&=65535;if(b<=C)break;if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if(0===(O&240)){I=b;N=O;for(F=G;;){G=c.distcode[F+((y&(1<<I+N)-1)>>I)];b=G>>>24;O=G>>>16&255;G&=65535;if(I+b<=C)break;if(0===z)break a;z--;y+=f[A++]<<C;C+=8}y>>>=I;C-=I;c.back+=I}y>>>=b;C-=b;c.back+=b;if(O&64){g.msg="invalid distance code";c.mode=30;break}c.offset=G;c.extra=O&15;c.mode=24;case 24:if(c.extra){for(O=c.extra;C<O;){if(0===z)break a;z--;
y+=f[A++]<<C;C+=8}c.offset+=y&(1<<c.extra)-1;y>>>=c.extra;C-=c.extra;c.back+=c.extra}if(c.offset>c.dmax){g.msg="invalid distance too far back";c.mode=30;break}c.mode=25;case 25:if(0===a)break a;b=K-a;if(c.offset>b){b=c.offset-b;if(b>c.whave&&c.sane){g.msg="invalid distance too far back";c.mode=30;break}b>c.wnext?(b-=c.wnext,O=c.wsize-b):O=c.wnext-b;b>c.length&&(b=c.length);I=c.window}else I=M,O=S-c.offset,b=c.length;b>a&&(b=a);a-=b;c.length-=b;do M[S++]=I[O++];while(--b);0===c.length&&(c.mode=21);
break;case 26:if(0===a)break a;M[S++]=c.length;a--;c.mode=21;break;case 27:if(c.wrap){for(;32>C;){if(0===z)break a;z--;y|=f[A++]<<C;C+=8}K-=a;g.total_out+=K;c.total+=K;K&&(g.adler=c.check=c.flags?h(c.check,M,K,S-K):d(c.check,M,K,S-K));K=a;if((c.flags?y:m(y))!==c.check){g.msg="incorrect data check";c.mode=30;break}C=y=0}c.mode=28;case 28:if(c.wrap&&c.flags){for(;32>C;){if(0===z)break a;z--;y+=f[A++]<<C;C+=8}if(y!==(c.total&4294967295)){g.msg="incorrect length check";c.mode=30;break}C=y=0}c.mode=29;
case 29:X=1;break a;case 30:X=-3;break a;case 31:return-4;default:return-2}g.next_out=S;g.avail_out=a;g.next_in=A;g.avail_in=z;c.hold=y;c.bits=C;if((c.wsize||K!==g.avail_out&&30>c.mode&&(27>c.mode||4!==D))&&l(g,g.output,g.next_out,K-g.avail_out))return c.mode=31,-4;T-=g.avail_in;K-=g.avail_out;g.total_in+=T;g.total_out+=K;c.total+=K;c.wrap&&K&&(g.adler=c.check=c.flags?h(c.check,M,K,g.next_out-K):d(c.check,M,K,g.next_out-K));g.data_type=c.bits+(c.last?64:0)+(12===c.mode?128:0)+(20===c.mode||15===c.mode?
256:0);(0===T&&0===K||4===D)&&0===X&&(X=-5);return X};B.inflateEnd=function(g){if(!g||!g.state)return-2;var D=g.state;D.window&&(D.window=null);g.state=null;return 0};B.inflateGetHeader=function(g,D){if(!g||!g.state)return-2;var F=g.state;if(0===(F.wrap&2))return-2;F.head=D;D.done=!1;return 0};B.inflateSetDictionary=function(g,D){var F=D.length;if(!g||!g.state)return-2;var H=g.state;if(0!==H.wrap&&11!==H.mode)return-2;if(11===H.mode){var L=d(1,D,F,0);if(L!==H.check)return-3}if(l(g,D,F,F))return H.mode=
31,-4;H.havedict=1;return 0};B.inflateInfo="pako inflate (from Nodeca project)"},{"../utils/common":41,"./adler32":43,"./crc32":45,"./inffast":48,"./inftrees":50}],50:[function(p,J,B){var m=p("../utils/common"),w=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],e=[16,16,16,16,16,16,16,16,17,17,17,17,18,18,18,18,19,19,19,19,20,20,20,20,21,21,21,21,16,72,78],n=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,
16385,24577,0,0],u=[16,16,16,16,17,17,18,18,19,19,20,20,21,21,22,22,23,23,24,24,25,25,26,26,27,27,28,28,29,29,64,64];J.exports=function(t,l,x,d,h,v,E,q){var k=q.bits,r,g,D,F,H,L,c=0,S=new m.Buf16(16);var M=new m.Buf16(16);var a,A=0;for(r=0;15>=r;r++)S[r]=0;for(g=0;g<d;g++)S[l[x+g]]++;var f=k;for(D=15;1<=D&&0===S[D];D--);f>D&&(f=D);if(0===D)return h[v++]=20971520,h[v++]=20971520,q.bits=1,0;for(k=1;k<D&&0===S[k];k++);f<k&&(f=k);for(r=F=1;15>=r;r++)if(F<<=1,F-=S[r],0>F)return-1;if(0<F&&(0===t||1!==D))return-1;
M[1]=0;for(r=1;15>r;r++)M[r+1]=M[r]+S[r];for(g=0;g<d;g++)0!==l[x+g]&&(E[M[l[x+g]]++]=g);if(0===t){var z=a=E;var y=19}else 1===t?(z=w,c-=257,a=e,A-=257,y=256):(z=n,a=u,y=-1);g=H=0;r=k;var C=v;d=f;M=0;var T=-1;var K=1<<f;var X=K-1;if(1===t&&852<K||2===t&&592<K)return 1;for(;;){var O=r-M;if(E[g]<y){var b=0;var G=E[g]}else E[g]>y?(b=a[A+E[g]],G=z[c+E[g]]):(b=96,G=0);F=1<<r-M;k=L=1<<d;do L-=F,h[C+(H>>M)+L]=O<<24|b<<16|G|0;while(0!==L);for(F=1<<r-1;H&F;)F>>=1;0!==F?(H&=F-1,H+=F):H=0;g++;if(0===--S[r]){if(r===
D)break;r=l[x+E[g]]}if(r>f&&(H&X)!==T){0===M&&(M=f);C+=k;d=r-M;for(F=1<<d;d+M<D;){F-=S[d+M];if(0>=F)break;d++;F<<=1}K+=1<<d;if(1===t&&852<K||2===t&&592<K)return 1;T=H&X;h[T]=f<<24|d<<16|C-v|0}}0!==H&&(h[C+H]=r-M<<24|4194304);q.bits=f;return 0}},{"../utils/common":41}],51:[function(p,J,B){J.exports={2:"need dictionary",1:"stream end",0:"","-1":"file error","-2":"stream error","-3":"data error","-4":"insufficient memory","-5":"buffer error","-6":"incompatible version"}},{}],52:[function(p,J,B){function m(b){for(var G=
b.length;0<=--G;)b[G]=0}function w(b,G,I,N,P){this.static_tree=b;this.extra_bits=G;this.extra_base=I;this.elems=N;this.max_length=P;this.has_stree=b&&b.length}function e(b,G){this.dyn_tree=b;this.max_code=0;this.stat_desc=G}function n(b,G){b.pending_buf[b.pending++]=G&255;b.pending_buf[b.pending++]=G>>>8&255}function u(b,G,I){b.bi_valid>16-I?(b.bi_buf|=G<<b.bi_valid&65535,n(b,b.bi_buf),b.bi_buf=G>>16-b.bi_valid,b.bi_valid+=I-16):(b.bi_buf|=G<<b.bi_valid&65535,b.bi_valid+=I)}function t(b,G,I){u(b,
I[2*G],I[2*G+1])}function l(b,G){var I=0;do I|=b&1,b>>>=1,I<<=1;while(0<--G);return I>>>1}function x(b,G,I){var N=Array(16),P=0,Q;for(Q=1;15>=Q;Q++)N[Q]=P=P+I[Q-1]<<1;for(I=0;I<=G;I++)P=b[2*I+1],0!==P&&(b[2*I]=l(N[P]++,P))}function d(b){var G;for(G=0;286>G;G++)b.dyn_ltree[2*G]=0;for(G=0;30>G;G++)b.dyn_dtree[2*G]=0;for(G=0;19>G;G++)b.bl_tree[2*G]=0;b.dyn_ltree[512]=1;b.opt_len=b.static_len=0;b.last_lit=b.matches=0}function h(b){8<b.bi_valid?n(b,b.bi_buf):0<b.bi_valid&&(b.pending_buf[b.pending++]=b.bi_buf);
b.bi_buf=0;b.bi_valid=0}function v(b,G,I,N){var P=2*G,Q=2*I;return b[P]<b[Q]||b[P]===b[Q]&&N[G]<=N[I]}function E(b,G,I){for(var N=b.heap[I],P=I<<1;P<=b.heap_len;){P<b.heap_len&&v(G,b.heap[P+1],b.heap[P],b.depth)&&P++;if(v(G,N,b.heap[P],b.depth))break;b.heap[I]=b.heap[P];I=P;P<<=1}b.heap[I]=N}function q(b,G,I){var N=0;if(0!==b.last_lit){do{var P=b.pending_buf[b.d_buf+2*N]<<8|b.pending_buf[b.d_buf+2*N+1];var Q=b.pending_buf[b.l_buf+N];N++;if(0===P)t(b,Q,G);else{var R=z[Q];t(b,R+256+1,G);var V=L[R];
0!==V&&(Q-=y[R],u(b,Q,V));P--;R=256>P?f[P]:f[256+(P>>>7)];t(b,R,I);V=c[R];0!==V&&(P-=C[R],u(b,P,V))}}while(N<b.last_lit)}t(b,256,G)}function k(b,G){var I=G.dyn_tree,N=G.stat_desc.static_tree,P=G.stat_desc.has_stree,Q=G.stat_desc.elems,R,V=-1;b.heap_len=0;b.heap_max=573;for(R=0;R<Q;R++)0!==I[2*R]?(b.heap[++b.heap_len]=V=R,b.depth[R]=0):I[2*R+1]=0;for(;2>b.heap_len;){var W=b.heap[++b.heap_len]=2>V?++V:0;I[2*W]=1;b.depth[W]=0;b.opt_len--;P&&(b.static_len-=N[2*W+1])}G.max_code=V;for(R=b.heap_len>>1;1<=
R;R--)E(b,I,R);W=Q;do R=b.heap[1],b.heap[1]=b.heap[b.heap_len--],E(b,I,1),N=b.heap[1],b.heap[--b.heap_max]=R,b.heap[--b.heap_max]=N,I[2*W]=I[2*R]+I[2*N],b.depth[W]=(b.depth[R]>=b.depth[N]?b.depth[R]:b.depth[N])+1,I[2*R+1]=I[2*N+1]=W,b.heap[1]=W++,E(b,I,1);while(2<=b.heap_len);b.heap[--b.heap_max]=b.heap[1];R=G.dyn_tree;W=G.max_code;var U=G.stat_desc.static_tree,ea=G.stat_desc.has_stree,fa=G.stat_desc.extra_bits,ca=G.stat_desc.extra_base,Y=G.stat_desc.max_length,Z=0;for(Q=0;15>=Q;Q++)b.bl_count[Q]=
0;R[2*b.heap[b.heap_max]+1]=0;for(N=b.heap_max+1;573>N;N++)if(P=b.heap[N],Q=R[2*R[2*P+1]+1]+1,Q>Y&&(Q=Y,Z++),R[2*P+1]=Q,!(P>W)){b.bl_count[Q]++;var ba=0;P>=ca&&(ba=fa[P-ca]);var da=R[2*P];b.opt_len+=da*(Q+ba);ea&&(b.static_len+=da*(U[2*P+1]+ba))}if(0!==Z){do{for(Q=Y-1;0===b.bl_count[Q];)Q--;b.bl_count[Q]--;b.bl_count[Q+1]+=2;b.bl_count[Y]--;Z-=2}while(0<Z);for(Q=Y;0!==Q;Q--)for(P=b.bl_count[Q];0!==P;)U=b.heap[--N],U>W||(R[2*U+1]!==Q&&(b.opt_len+=(Q-R[2*U+1])*R[2*U],R[2*U+1]=Q),P--)}x(I,V,b.bl_count)}
function r(b,G,I){var N,P=-1,Q=G[1],R=0,V=7,W=4;0===Q&&(V=138,W=3);G[2*(I+1)+1]=65535;for(N=0;N<=I;N++){var U=Q;Q=G[2*(N+1)+1];++R<V&&U===Q||(R<W?b.bl_tree[2*U]+=R:0!==U?(U!==P&&b.bl_tree[2*U]++,b.bl_tree[32]++):10>=R?b.bl_tree[34]++:b.bl_tree[36]++,R=0,P=U,0===Q?(V=138,W=3):U===Q?(V=6,W=3):(V=7,W=4))}}function g(b,G,I){var N,P=-1,Q=G[1],R=0,V=7,W=4;0===Q&&(V=138,W=3);for(N=0;N<=I;N++){var U=Q;Q=G[2*(N+1)+1];if(!(++R<V&&U===Q)){if(R<W){do t(b,U,b.bl_tree);while(0!==--R)}else 0!==U?(U!==P&&(t(b,U,
b.bl_tree),R--),t(b,16,b.bl_tree),u(b,R-3,2)):10>=R?(t(b,17,b.bl_tree),u(b,R-3,3)):(t(b,18,b.bl_tree),u(b,R-11,7));R=0;P=U;0===Q?(V=138,W=3):U===Q?(V=6,W=3):(V=7,W=4)}}}function D(b){var G=4093624447,I;for(I=0;31>=I;I++,G>>>=1)if(G&1&&0!==b.dyn_ltree[2*I])return 0;if(0!==b.dyn_ltree[18]||0!==b.dyn_ltree[20]||0!==b.dyn_ltree[26])return 1;for(I=32;256>I;I++)if(0!==b.dyn_ltree[2*I])return 1;return 0}function F(b,G,I,N){u(b,N?1:0,3);h(b);n(b,I);n(b,~I);H.arraySet(b.pending_buf,b.window,G,I,b.pending);
b.pending+=I}var H=p("../utils/common"),L=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],c=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],S=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,7],M=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],a=Array(576);m(a);var A=Array(60);m(A);var f=Array(512);m(f);var z=Array(256);m(z);var y=Array(29);m(y);var C=Array(30);m(C);var T,K,X,O=!1;B._tr_init=function(b){if(!O){var G,I,N,P=Array(16);for(N=I=0;28>N;N++)for(y[N]=I,G=0;G<1<<L[N];G++)z[I++]=
N;z[I-1]=N;for(N=I=0;16>N;N++)for(C[N]=I,G=0;G<1<<c[N];G++)f[I++]=N;for(I>>=7;30>N;N++)for(C[N]=I<<7,G=0;G<1<<c[N]-7;G++)f[256+I++]=N;for(G=0;15>=G;G++)P[G]=0;for(G=0;143>=G;)a[2*G+1]=8,G++,P[8]++;for(;255>=G;)a[2*G+1]=9,G++,P[9]++;for(;279>=G;)a[2*G+1]=7,G++,P[7]++;for(;287>=G;)a[2*G+1]=8,G++,P[8]++;x(a,287,P);for(G=0;30>G;G++)A[2*G+1]=5,A[2*G]=l(G,5);T=new w(a,L,257,286,15);K=new w(A,c,0,30,15);X=new w([],S,0,19,7);O=!0}b.l_desc=new e(b.dyn_ltree,T);b.d_desc=new e(b.dyn_dtree,K);b.bl_desc=new e(b.bl_tree,
X);b.bi_buf=0;b.bi_valid=0;d(b)};B._tr_stored_block=F;B._tr_flush_block=function(b,G,I,N){var P=0;if(0<b.level){2===b.strm.data_type&&(b.strm.data_type=D(b));k(b,b.l_desc);k(b,b.d_desc);r(b,b.dyn_ltree,b.l_desc.max_code);r(b,b.dyn_dtree,b.d_desc.max_code);k(b,b.bl_desc);for(P=18;3<=P&&0===b.bl_tree[2*M[P]+1];P--);b.opt_len+=3*(P+1)+14;var Q=b.opt_len+3+7>>>3;var R=b.static_len+3+7>>>3;R<=Q&&(Q=R)}else Q=R=I+5;if(I+4<=Q&&-1!==G)F(b,G,I,N);else if(4===b.strategy||R===Q)u(b,2+(N?1:0),3),q(b,a,A);else{u(b,
4+(N?1:0),3);G=b.l_desc.max_code+1;I=b.d_desc.max_code+1;P+=1;u(b,G-257,5);u(b,I-1,5);u(b,P-4,4);for(Q=0;Q<P;Q++)u(b,b.bl_tree[2*M[Q]+1],3);g(b,b.dyn_ltree,G-1);g(b,b.dyn_dtree,I-1);q(b,b.dyn_ltree,b.dyn_dtree)}d(b);N&&h(b)};B._tr_tally=function(b,G,I){b.pending_buf[b.d_buf+2*b.last_lit]=G>>>8&255;b.pending_buf[b.d_buf+2*b.last_lit+1]=G&255;b.pending_buf[b.l_buf+b.last_lit]=I&255;b.last_lit++;0===G?b.dyn_ltree[2*I]++:(b.matches++,G--,b.dyn_ltree[2*(z[I]+256+1)]++,b.dyn_dtree[2*(256>G?f[G]:f[256+(G>>>
7)])]++);return b.last_lit===b.lit_bufsize-1};B._tr_align=function(b){u(b,2,3);t(b,256,a);16===b.bi_valid?(n(b,b.bi_buf),b.bi_buf=0,b.bi_valid=0):8<=b.bi_valid&&(b.pending_buf[b.pending++]=b.bi_buf&255,b.bi_buf>>=8,b.bi_valid-=8)}},{"../utils/common":41}],53:[function(p,J,B){J.exports=function(){this.input=null;this.total_in=this.avail_in=this.next_in=0;this.output=null;this.total_out=this.avail_out=this.next_out=0;this.msg="";this.state=null;this.data_type=2;this.adler=0}},{}],54:[function(p,J,B){J.exports=
"function"===typeof setImmediate?setImmediate:function(){var m=[].slice.apply(arguments);m.splice(1,0,0);setTimeout.apply(null,m)}},{}]},{},[10])(10)});